import { useEffect, useState } from 'react';
import { topics, LearningProgress } from '../lib/curriculum';
import { PLAN_MODULES } from '../lib/plan';
import { getTopicVideos } from '../lib/learning-videos';
import { VideoReferences } from './VideoReferences';
import { sectionExamples } from '../lib/topic-examples';
import { ExplainedExample } from './ExplainedExample';

export function LearningZone({topicId,onSelect,progress,onProgress,onSQL,onInterview}:{topicId:number;onSelect:(id:number)=>void;progress:LearningProgress;onProgress:(next:LearningProgress)=>void;onSQL:()=>void;onInterview:()=>void}) {
  const [search,setSearch]=useState('');
  const [choice,setChoice]=useState<number|null>(null);
  const [checked,setChecked]=useState(false);
  useEffect(()=>{setChoice(null);setChecked(false);},[topicId]);
  const topic=topics.find(t=>t.id===topicId)||topics[0];
  function select(id:number){onSelect(id);setChoice(null);setChecked(false);}
  const record = (field:'quizzes'|'labs',id:number,add:boolean) => onProgress({...progress,[field]:add?[...new Set([...progress[field],id])]:progress[field].filter(x=>x!==id)});
  return <>
    <div className="section-head"><div><h2>Learning Zone</h2><span>A guided route through your 24-topic checklist</span></div><button className="btn" onClick={onSQL}>SQL Studio · 32 lessons →</button></div>
    <div className="learning-shell"><aside className="card curriculum-nav"><label htmlFor="topic-search">Find a topic</label><input id="topic-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Python, quality, interviews…"/>{PLAN_MODULES.map(m=><div key={m.id}><div className="group-label">{m.title}</div>{m.items.filter(i=>{const t=topics.find(t=>t.id===i.id)!;return (i.label+' '+t.title).toLowerCase().includes(search.toLowerCase())}).map(i=><button aria-current={topic.id===i.id?'page':undefined} className={topic.id===i.id?'selected':''} key={i.id} onClick={()=>select(i.id)}><span>{String(i.id).padStart(2,'0')}</span>{topics.find(t=>t.id===i.id)!.title}{progress.quizzes.includes(i.id)&&<small aria-label="Knowledge check passed">✓</small>}</button>)}</div>)}</aside>
    <article className="classroom" key={topic.id}>
      <div className="topic-banner card card-pad"><div className="eyebrow">DATA ENGINEERING · TOPIC {topic.id} OF 24</div><h1>{topic.title}</h1><p>{topic.objective}</p><div className="environment-label">{topic.environment}</div>{topic.prerequisites.length>0&&<div className="prerequisite-links"><b>Before this topic:</b>{topic.prerequisites.map(id=><button className="link-btn" key={id} onClick={()=>select(id)}>{topics.find(t=>t.id===id)!.title}</button>)}</div>}<p className="learning-method">Learn → predict the example → try the task → review your evidence → check understanding</p></div>
      {topic.sections.map(([title,text],index)=><section className="card card-pad teaching-section" key={title}><div className="eyebrow">{String(index+1).padStart(2,'0')} · UNDERSTAND</div><h2>{title}</h2><p>{text}</p><ExplainedExample example={sectionExamples[topic.id][index]}/></section>)}
      <VideoReferences videos={getTopicVideos(topic.id)}/>
      <section className="card card-pad teaching-section"><div className="eyebrow">WORKED EXAMPLE</div><h2>Follow the idea in action</h2><p>Predict what this produces before running or tracing it. The environment label tells you where it belongs.</p><div className="sql-box"><div className="sql-head"><span>{topic.language}</span></div><pre className="sql-code">{topic.example}</pre></div>{[3,7,13,21].includes(topic.id)?<button className="btn primary" onClick={onSQL}>Open SQL Studio →</button>:null}<div className="tip-box"><b>Watch for this mistake:</b> {topic.mistake}</div></section>
      <section className="card card-pad teaching-section"><div className="eyebrow">DO THE WORK</div><h2>Your practical task</h2><p>{topic.task}</p><h3>Evidence to review</h3><ul>{topic.rubric.map(line=><li key={line}>{line}</li>)}</ul><details><summary>Compare with the instructor’s approach</summary><p>{topic.solution}</p></details><label htmlFor="evidence-notes">Your reasoning, results, and evidence links</label><textarea id="evidence-notes" value={progress.notes[String(topic.id)]||''} maxLength={12000} placeholder="What did you try? What happened? How did you verify it? Keep credentials and private data out of these notes." onChange={e=>onProgress({...progress,notes:{...progress.notes,[String(topic.id)]:e.target.value}})}/><button className="btn" aria-pressed={progress.labs.includes(topic.id)} onClick={()=>record('labs',topic.id,!progress.labs.includes(topic.id))}>{progress.labs.includes(topic.id)?'✓ Task reviewed · self-reported':'I completed the task and reviewed the evidence'}</button><small className="progress-disclosure">Task completion is your own record. The site does not execute or assess external labs.</small></section>
      <section className="card card-pad teaching-section"><div className="eyebrow">CHECK UNDERSTANDING</div><h2>{topic.question}</h2><fieldset className="quiz-options"><legend className="sr-only">Choose an answer</legend>{topic.options.map((option,index)=><label key={option}><input type="radio" name={'topic-'+topic.id} checked={choice===index} onChange={()=>{setChoice(index);setChecked(false);}}/>{option}</label>)}</fieldset><button className="btn primary" disabled={choice===null} onClick={()=>{setChecked(true);if(choice===topic.answer)record('quizzes',topic.id,true);}}>Check answer</button>{checked&&<div role="status" className="tip-box"><b>{choice===topic.answer?'Correct.':'Try again.'}</b> {topic.feedback}</div>}{progress.quizzes.includes(topic.id)&&<p>✓ Knowledge check passed. This confirms this question, not mastery of the entire topic.</p>}</section>
      {[16,17,18].includes(topic.id)&&<section className="card card-pad teaching-section"><div className="eyebrow">DOWNLOADABLE PRACTICE</div><h2>A runnable starting point</h2><p>Save these files into a new local practice directory. Read the code, run its checks, then extend it using this topic’s rubric. These are standard-library Python labs, separate from a cloud deployment.</p><div className="actions"><a className="btn" href="/labs/batch_pipeline.py" download>Batch pipeline starter</a><a className="btn" href="/labs/orders.csv" download>Synthetic orders CSV</a><a className="btn" href="/labs/stream_replay.py" download>Stream replay simulator</a></div><pre className="sql-code">python batch_pipeline.py --self-test{'\n'}python batch_pipeline.py --input orders.csv --output output{'\n'}python stream_replay.py</pre><p>Expected: paid daily revenue 120 and 80; one rejected input; stream replay total 60. Extend with deletes, late-event policy, and failure injection. The batch starter records its atomicity limits in the manifest.</p></section>}
      <section className="card card-pad teaching-section"><h2>Go deeper with official references</h2><p>Examples teach the core idea. For external tools, check the documentation matching your installed version before running commands.</p><ul>{topic.sources.map(([label,url])=><li key={url}><a href={url} target="_blank" rel="noreferrer">{label} ↗</a></li>)}</ul>{[21,24].includes(topic.id)?<button className="btn" onClick={onInterview}>Open SQL Interview Mode →</button>:null}</section>
      <div className="lesson-nav"><button className="btn" disabled={topic.id===1} onClick={()=>select(topic.id-1)}>← Previous topic</button><span>{topic.id} / 24</span><button className="btn primary" disabled={topic.id===24} onClick={()=>select(topic.id+1)}>Next topic →</button></div>
    </article></div>
  </>;
}
