import { Lesson, LessonSeed, Project, Exercise, CaseStudy } from "../types";

export const lessonSeeds: LessonSeed[] = [
  ["SELECT","Your First SELECT","FOUNDATIONS","Choose the columns you need and understand the grain of a table.","SELECT customer_id, name\nFROM customers;","SELECT chooses columns; FROM chooses the source table.","Start with the business question, then choose only the columns needed."],
  ["WHERE","Filtering with WHERE","FOUNDATIONS","Filter rows using equality, ranges, IN, BETWEEN and boolean logic.","SELECT name, city\nFROM customers\nWHERE city = 'Delhi';","WHERE filters rows before aggregation.","Put row-level filters in WHERE, not HAVING."],
  ["ORDER","Sorting Results","FOUNDATIONS","Control result order with ASC, DESC and multiple sort keys.","SELECT name, lifetime_value\nFROM customers\nORDER BY lifetime_value DESC;","ORDER BY changes presentation, not the underlying data.","Always add a deterministic tie-breaker when order matters."],
  ["DISTINCT","DISTINCT & Duplicates","FOUNDATIONS","Return unique values and recognize when duplicates are meaningful.","SELECT DISTINCT city\nFROM customers\nORDER BY city;","DISTINCT removes duplicate result rows.","Do not use DISTINCT to hide a bad join."],
  ["NULL","NULL & Missing Data","FOUNDATIONS","Handle unknown or missing values correctly with IS NULL, COALESCE and NULL-safe logic.","SELECT *\nFROM customers\nWHERE lifetime_value IS NULL;","NULL is not equal to 0 or an empty string.","Use IS NULL / IS NOT NULL for missingness checks."],
  ["CASE","CASE WHEN","FOUNDATIONS","Turn raw values into business categories, flags and buckets.","SELECT name, CASE WHEN lifetime_value >= 50000 THEN 'VIP' ELSE 'Core' END AS segment\nFROM customers;","CASE embeds business rules in SQL.","Order overlapping conditions from most specific to least specific."],
  ["COUNT","COUNT & Aggregates","AGGREGATION","Use COUNT, SUM, AVG, MIN and MAX to create metrics.","SELECT COUNT(*) AS customers, AVG(lifetime_value) AS avg_ltv\nFROM customers;","Aggregates summarize many rows into metrics.","COUNT(*) counts rows; COUNT(column) ignores NULLs."],
  ["GROUP","GROUP BY","AGGREGATION","Move from row-level data to segmented reporting.","SELECT city, COUNT(*) AS customers\nFROM customers\nGROUP BY city;","GROUP BY creates one result row per group.","Every selected non-aggregated column generally belongs in GROUP BY."],
  ["HAVING","HAVING","AGGREGATION","Filter aggregated groups after GROUP BY.","SELECT city, SUM(amount) AS revenue\nFROM orders o JOIN customers c ON c.customer_id=o.customer_id\nGROUP BY city\nHAVING SUM(amount) > 30000;","WHERE filters rows; HAVING filters groups.","If the condition depends on an aggregate, think HAVING."],
  ["JOIN","INNER JOIN","JOINS","Combine matching records across related tables.","SELECT c.name, o.amount\nFROM customers c\nJOIN orders o ON c.customer_id=o.customer_id;","INNER JOIN keeps matching records from both tables.","Before joining, state the grain of each table and the expected row multiplication."],
  ["LEFT","LEFT JOIN","JOINS","Preserve the left table to find missing relationships.","SELECT c.name\nFROM customers c\nLEFT JOIN orders o ON c.customer_id=o.customer_id\nWHERE o.order_id IS NULL;","LEFT JOIN is the classic pattern for 'who did not...' questions.","A WHERE condition on the right table can accidentally turn a LEFT JOIN into an INNER JOIN."],
  ["MULTI","Multi-table Joins","JOINS","Join three or more tables while keeping keys and grain under control.","SELECT o.order_id, c.name, p.category\nFROM orders o\nJOIN customers c ON c.customer_id=o.customer_id\nJOIN products p ON p.product_id=o.product_id;","Multiple joins are a chain of relationships.","Validate row counts after each join when debugging duplicates."],
  ["SUBQUERY","Subqueries","INTERMEDIATE","Use a query inside another query for filtering or derived metrics.","SELECT name\nFROM customers\nWHERE customer_id IN (SELECT customer_id FROM orders);","Subqueries let one query feed another.","If nested logic becomes hard to read, consider a CTE."],
  ["CTE","Common Table Expressions","INTERMEDIATE","Break complex analytical SQL into named, testable steps.","WITH revenue AS (SELECT customer_id, SUM(amount) total FROM orders GROUP BY customer_id)\nSELECT * FROM revenue ORDER BY total DESC;","CTEs improve structure and debugging.","Build one logical step at a time and inspect intermediate results."],
  ["UNION","UNION & UNION ALL","INTERMEDIATE","Stack compatible result sets vertically.","SELECT customer_id FROM web_customers\nUNION ALL\nSELECT customer_id FROM store_customers;","UNION removes duplicates; UNION ALL preserves them.","The two SELECTs must have compatible column positions and types."],
  ["EXISTS","EXISTS & Anti-Joins","INTERMEDIATE","Check whether a related record exists without needing its columns.","SELECT c.name\nFROM customers c\nWHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id=c.customer_id);","EXISTS answers 'does a matching row exist?'.","EXISTS is often cleaner than DISTINCT when you only need presence."],
  ["DATES","Date SQL","INTERMEDIATE","Extract periods, calculate date differences and build monthly reporting.","SELECT DATE_TRUNC('month', order_date) AS month, SUM(amount) AS revenue\nFROM orders\nGROUP BY 1\nORDER BY 1;","Dates are essential for trend and cohort analysis.","Choose the reporting grain explicitly: day, week, month or quarter."],
  ["ROW","ROW_NUMBER","WINDOWS","Rank rows within groups without collapsing the dataset.","SELECT customer_id, order_date, amount, ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY order_date) AS purchase_no\nFROM orders;","ROW_NUMBER assigns a unique sequence inside each partition.","Use it to select first/last records and top-N-per-group."],
  ["RANK","RANK & DENSE_RANK","WINDOWS","Compare ranking functions and how ties are handled.","SELECT name, lifetime_value, RANK() OVER(ORDER BY lifetime_value DESC) AS rnk\nFROM customers;","RANK leaves gaps after ties; DENSE_RANK does not.","Pick the ranking function based on the business definition of ties."],
  ["LAG","LAG & LEAD","WINDOWS","Compare a row with the previous or next row.","SELECT month, revenue, LAG(revenue) OVER(ORDER BY month) AS prior_month\nFROM monthly_revenue;","LAG and LEAD create period-over-period comparisons.","Always define the ORDER BY that determines what 'previous' means."],
  ["RUNNING","Running Totals","WINDOWS","Calculate cumulative metrics while retaining row-level detail.","SELECT order_date, amount, SUM(amount) OVER(ORDER BY order_date) AS running_revenue\nFROM orders;","A windowed SUM can accumulate values over time.","For business reporting, confirm whether the running total needs PARTITION BY."],
  ["MOVING","Moving Averages","WINDOWS","Smooth noisy time series with rolling windows.","AVG(revenue) OVER(ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)","Moving averages summarize a rolling period.","A three-row window is not always a three-month window if dates are missing."],
  ["COHORT","Cohort Analysis","ANALYST SQL","Group users by signup period and compare behavior over time.","WITH cohorts AS (SELECT customer_id, DATE_TRUNC('month', signup_date) cohort_month FROM customers) SELECT cohort_month, COUNT(*) FROM cohorts GROUP BY 1;","Cohorts make lifecycle behavior comparable.","Separate cohort assignment from activity measurement."],
  ["RETENTION","Retention","ANALYST SQL","Measure how many users remain active after signup or a prior period.","SELECT cohort_month, activity_month, COUNT(DISTINCT customer_id) active_users\nFROM activity\nGROUP BY 1,2;","Retention is a relationship between a cohort and later activity.","Define the retention event before writing SQL."],
  ["CHURN","Churn & Reactivation","ANALYST SQL","Identify inactive customers and distinguish churn from temporary inactivity.","WITH last_seen AS (SELECT customer_id, MAX(event_date) last_seen FROM events GROUP BY 1) SELECT * FROM last_seen;","Churn requires a clear inactivity window.","Write the business definition first: e.g. no activity for 60 days."],
  ["FUNNEL","Funnel Analysis","ANALYST SQL","Measure progression from one event to the next.","SELECT COUNT(DISTINCT CASE WHEN event='view' THEN user_id END) views, COUNT(DISTINCT CASE WHEN event='purchase' THEN user_id END) buyers FROM events;","Funnels quantify conversion between stages.","Use DISTINCT users when the metric is user conversion, not event volume."],
  ["SEGMENT","Customer Segmentation","ANALYST SQL","Create useful segments from behavior, value and recency.","CASE WHEN orders_90d >= 5 AND spend_90d >= 50000 THEN 'High Value' ... END","Segments translate metrics into action-oriented groups.","Make thresholds explicit and validate segment sizes."],
  ["KPI","KPI Design in SQL","ANALYST SQL","Build trustworthy metrics with numerators, denominators and grain.","SELECT SUM(resolved_within_sla)::DOUBLE / NULLIF(COUNT(*),0) AS sla_rate FROM tickets;","A KPI is a definition, not just a SQL expression.","Always validate numerator, denominator, time window and population."],
  ["QUALITY","Data Quality Checks","ANALYST SQL","Detect duplicates, missing keys, invalid dates and broken relationships.","SELECT customer_id, COUNT(*) FROM customers GROUP BY 1 HAVING COUNT(*) > 1;","Quality SQL protects downstream analysis.","Turn recurring checks into reusable validation queries."],
  ["PERF","SQL Performance Thinking","ADVANCED","Reason about filters, joins, aggregation and query plans.","SELECT ... FROM large_fact f JOIN dim d ON ... WHERE f.event_date >= DATE '2026-01-01';","Correct SQL comes first; performance follows from data volume and execution strategy.","Filter early, join on keys, avoid unnecessary columns and inspect plans when available."],
  ["DEBUG","Debugging SQL","ADVANCED","Use row counts, samples and intermediate CTEs to isolate errors.","WITH step1 AS (...), step2 AS (...) SELECT COUNT(*) FROM step2;","Debugging is a repeatable process, not guesswork.","Compare expected grain with actual grain after every transformation."],
  ["PROJECT","Analyst SQL Project","CAPSTONE","Combine joins, windows, KPIs and business reasoning in a full analysis.","WITH ... SELECT ...;","A senior analyst explains what the query means for the business.","Finish with an insight, implication and recommended next question."],
];

export const lessons: Lesson[] = lessonSeeds.map(([key,title,level,text,sql,takeaway,tip],i)=>({id:i+1,title,level,text,sql,takeaway,tip}));

export const customers = `CREATE TABLE customers(customer_id INTEGER,name VARCHAR,city VARCHAR,signup_date DATE,lifetime_value DOUBLE); INSERT INTO customers VALUES
(101,'Aarav Sharma','Delhi','2025-01-12',54000),(102,'Meera Kapoor','Mumbai','2025-02-18',28600),(103,'Kabir Singh','Delhi','2025-03-02',41200),(104,'Ananya Iyer','Bengaluru','2025-03-29',19800),(105,'Rohan Mehta','Pune','2025-04-10',62000),(106,'Simran Kaur','Delhi','2025-05-15',33700),(107,'Arjun Verma','Mumbai','2025-06-21',24100),(108,'Ishita Rao','Hyderabad','2025-07-03',15800);`;
export const orders = `CREATE TABLE orders(order_id INTEGER,customer_id INTEGER,product_id INTEGER,order_date DATE,amount DOUBLE,channel VARCHAR); INSERT INTO orders VALUES
(1001,101,1,'2026-01-04',12500,'Online'),(1002,101,2,'2026-01-19',8300,'Online'),(1003,102,3,'2026-01-11',5600,'Store'),(1004,103,1,'2026-01-08',14300,'Online'),(1005,103,4,'2026-02-02',9200,'Partner'),(1006,104,2,'2026-02-06',4400,'Online'),(1007,105,5,'2026-02-10',18100,'Online'),(1008,105,1,'2026-02-18',11200,'Partner'),(1009,106,3,'2026-02-21',7600,'Store'),(1010,107,2,'2026-03-01',6900,'Online'),(1011,101,5,'2026-03-03',15200,'Online'),(1012,108,4,'2026-03-05',3200,'Store'),(1013,102,1,'2026-03-08',8100,'Online'),(1014,105,5,'2026-03-09',9900,'Online'),(1015,106,3,'2026-03-12',6100,'Partner'),(1016,103,4,'2026-03-15',11700,'Online');`;
export const products = `CREATE TABLE products(product_id INTEGER,product_name VARCHAR,category VARCHAR,unit_price DOUBLE); INSERT INTO products VALUES (1,'Premium Plan','Subscription',12000),(2,'Analytics Pack','Software',8000),(3,'Support Bundle','Service',5500),(4,'Data Connector','Software',9500),(5,'Enterprise License','Subscription',18000);`;
export const healthcare = `CREATE TABLE members(member_id INTEGER,segment VARCHAR,state VARCHAR,age_band VARCHAR); INSERT INTO members VALUES (1,'Commercial','DL','18-34'),(2,'Commercial','MH','35-49'),(3,'Medicare','CA','65+'),(4,'Medicaid','TX','18-34'),(5,'Commercial','NY','50-64'),(6,'Medicare','FL','65+'),(7,'Medicaid','CA','35-49'),(8,'Commercial','WA','35-49');
CREATE TABLE claims(claim_id INTEGER,member_id INTEGER,provider_id INTEGER,drug VARCHAR,claim_date DATE,paid_amount DOUBLE,status VARCHAR); INSERT INTO claims VALUES (1,1,101,'DrugA','2026-01-04',120,'Paid'),(2,1,101,'DrugB','2026-01-19',410,'Paid'),(3,2,102,'DrugA','2026-01-20',130,'Paid'),(4,3,103,'DrugC','2026-01-22',980,'Paid'),(5,4,104,'DrugA','2026-02-02',160,'Paid'),(6,5,105,'DrugD','2026-02-04',740,'Paid'),(7,6,103,'DrugC','2026-02-11',1100,'Paid'),(8,7,104,'DrugB','2026-02-15',390,'Paid'),(9,8,106,'DrugD','2026-02-18',680,'Paid'),(10,2,102,'DrugB','2026-03-01',450,'Paid'),(11,3,103,'DrugC','2026-03-04',1020,'Paid'),(12,1,101,'DrugA','2026-03-07',125,'Paid');
CREATE TABLE providers(provider_id INTEGER,provider_name VARCHAR,specialty VARCHAR,network_status VARCHAR); INSERT INTO providers VALUES (101,'North Clinic','Primary Care','In Network'),(102,'Metro Health','Primary Care','In Network'),(103,'Sunrise Medical','Specialist','In Network'),(104,'Community Care','Primary Care','Out of Network'),(105,'Harbor Health','Specialist','In Network'),(106,'Evergreen Clinic','Primary Care','In Network');`;
export const contact = `CREATE TABLE agents(agent_id INTEGER,agent_name VARCHAR,team VARCHAR); INSERT INTO agents VALUES (1,'Aditi','Alpha'),(2,'Rahul','Alpha'),(3,'Neha','Beta'),(4,'Vikram','Beta'),(5,'Simran','Gamma'),(6,'Karan','Gamma');
CREATE TABLE calls(call_id INTEGER,agent_id INTEGER,call_date DATE,queue VARCHAR,handle_seconds INTEGER,wait_seconds INTEGER,resolved BOOLEAN,abandoned BOOLEAN); INSERT INTO calls VALUES (1,1,'2026-03-01','Billing',520,35,true,false),(2,2,'2026-03-01','Billing',710,58,true,false),(3,3,'2026-03-01','Claims',830,95,false,false),(4,4,'2026-03-01','Claims',640,120,true,false),(5,5,'2026-03-01','Benefits',440,25,true,false),(6,6,'2026-03-01','Benefits',920,160,false,false),(7,1,'2026-03-02','Billing',610,42,true,false),(8,2,'2026-03-02','Claims',780,130,true,false),(9,3,'2026-03-02','Claims',910,180,false,true),(10,4,'2026-03-02','Benefits',590,45,true,false),(11,5,'2026-03-02','Benefits',480,30,true,false),(12,6,'2026-03-02','Billing',860,150,true,false);`;
export const streaming = `CREATE TABLE subscribers(subscriber_id INTEGER,plan VARCHAR,signup_date DATE,region VARCHAR); INSERT INTO subscribers VALUES (1,'Premium','2025-11-01','North'),(2,'Basic','2025-11-03','West'),(3,'Premium','2025-12-10','North'),(4,'Basic','2025-12-18','South'),(5,'Premium','2026-01-05','West'),(6,'Basic','2026-01-12','East'),(7,'Premium','2026-01-18','North'),(8,'Basic','2026-02-01','South');
CREATE TABLE viewing(subscriber_id INTEGER,content_id INTEGER,view_date DATE,minutes INTEGER); INSERT INTO viewing VALUES (1,1,'2026-02-01',120),(1,2,'2026-02-05',80),(2,3,'2026-02-02',35),(3,1,'2026-02-03',150),(3,4,'2026-02-07',100),(4,2,'2026-02-10',25),(5,4,'2026-02-12',140),(5,5,'2026-02-14',90),(6,3,'2026-02-15',45),(7,1,'2026-02-17',180),(8,2,'2026-02-18',20);`;

export const datasets = [
  {id:'commerce',name:'Customer Commerce',icon:'🛒',description:'Customers, orders and products for core analyst SQL.',seed:`${customers}\n${orders}\n${products}`,tables:['customers','orders','products']},
  {id:'healthcare',name:'Pharmacy Claims',icon:'🏥',description:'Members, pharmacy claims and providers for healthcare analytics.',seed:healthcare,tables:['members','claims','providers']},
  {id:'contact',name:'Contact Center',icon:'📞',description:'Calls and agents for AHT, SLA and operations analysis.',seed:contact,tables:['agents','calls']},
  {id:'streaming',name:'Streaming',icon:'🎬',description:'Subscribers and viewing events for retention and engagement.',seed:streaming,tables:['subscribers','viewing']},
];

export const exercises: Exercise[] = [
  {id:1,dataset:'commerce',title:'Find Delhi Customers',difficulty:'Beginner',topic:'WHERE',prompt:'Return customer_id, name and lifetime_value for Delhi customers, highest LTV first.',starter:"SELECT customer_id, name, lifetime_value\nFROM customers\nWHERE city = 'Delhi'\nORDER BY lifetime_value DESC;",hints:['Filter city in WHERE, then sort lifetime_value DESC.','SELECT customer_id, name, lifetime_value
FROM customers
WHERE city = '''Delhi'''
ORDER BY lifetime_value DESC;','SELECT customer_id, name, lifetime_value
FROM customers
WHERE city = '''Delhi'''
ORDER BY lifetime_value DESC;'],explanation:'This combines row filtering and deterministic presentation.',check:r=>r.length===3&&'lifetime_value' in r[0]},
  {id:2,dataset:'commerce',title:'Revenue by City',difficulty:'Intermediate',topic:'GROUP BY',prompt:'Join customers and orders. Return city and total revenue, highest first.',starter:'SELECT c.city, SUM(o.amount) AS revenue\nFROM customers c\nJOIN orders o ON c.customer_id=o.customer_id\nGROUP BY c.city\nORDER BY revenue DESC;',hints:['The city is in customers; amount is in orders.', 'SELECT c.city, SUM(o.amount) AS revenue
FROM customers c
JOIN orders o ON c.customer_id=o.customer_id
GROUP BY c.city
ORDER BY revenue DESC;', 'SELECT c.city, SUM(o.amount) AS revenue
FROM customers c
JOIN orders o ON c.customer_id=o.customer_id
GROUP BY c.city
ORDER BY revenue DESC;'],explanation:'Join at customer grain, then aggregate order facts by city.',check:r=>r.length>=4&&'revenue' in r[0]},
  {id:3,dataset:'commerce',title:'Top Customer per City',difficulty:'Hard',topic:'WINDOWS',prompt:'Return the highest-revenue customer in each city with city, name and revenue.',starter:'WITH revenue AS (SELECT c.city,c.name,SUM(o.amount) revenue FROM customers c JOIN orders o ON c.customer_id=o.customer_id GROUP BY 1,2), ranked AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY city ORDER BY revenue DESC) rn FROM revenue) SELECT city,name,revenue FROM ranked WHERE rn=1 ORDER BY city;',hints:['Aggregate first, rank inside each city second.', 'WITH revenue AS (SELECT c.city,c.name,SUM(o.amount) revenue FROM customers c JOIN orders o ON c.customer_id=o.customer_id GROUP BY 1,2) SELECT * FROM revenue;', 'WITH revenue AS (SELECT c.city,c.name,SUM(o.amount) revenue FROM customers c JOIN orders o ON c.customer_id=o.customer_id GROUP BY 1,2), ranked AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY city ORDER BY revenue DESC) rn FROM revenue) SELECT city,name,revenue FROM ranked WHERE rn=1 ORDER BY city;'],explanation:'This is a classic senior analyst top-N-per-group pattern.',check:r=>r.length>=4&&r.every(x=>'revenue' in x&&'city' in x)},
  {id:4,dataset:'commerce',title:'VIP Segmentation',difficulty:'Intermediate',topic:'CASE',prompt:'Return each customer name and segment: VIP >= 50000, Core 25000–49999, Emerging below 25000.',starter:"SELECT name, CASE WHEN lifetime_value>=50000 THEN 'VIP' WHEN lifetime_value>=25000 THEN 'Core' ELSE 'Emerging' END AS segment FROM customers;",hints:['CASE evaluates conditions from top to bottom.', 'SELECT name, CASE WHEN lifetime_value>=50000 THEN 'VIP' WHEN lifetime_value>=25000 THEN 'Core' ELSE 'Emerging' END AS segment FROM customers;', 'SELECT name, CASE WHEN lifetime_value>=50000 THEN 'VIP' WHEN lifetime_value>=25000 THEN 'Core' ELSE 'Emerging' END AS segment FROM customers;'],explanation:'Business segmentation is a direct application of CASE.',check:r=>r.length===8&&'segment' in r[0]},
  {id:5,dataset:'healthcare',title:'Spend by Drug',difficulty:'Intermediate',topic:'Healthcare',prompt:'Calculate paid pharmacy spend by drug, highest spend first.',starter:'SELECT drug, SUM(paid_amount) AS spend\nFROM claims\nGROUP BY drug\nORDER BY spend DESC;',hints:['The fact table is claims and paid_amount is the spend measure.', 'SELECT drug, SUM(paid_amount) AS spend
FROM claims
GROUP BY drug
ORDER BY spend DESC;', 'SELECT drug, SUM(paid_amount) AS spend
FROM claims
GROUP BY drug
ORDER BY spend DESC;'],explanation:'A clean category KPI: group the claim facts by drug.',check:r=>r.length>=4&&'spend' in r[0]},
  {id:6,dataset:'healthcare',title:'Out-of-Network Spend',difficulty:'Hard',topic:'JOIN',prompt:'Return provider_name and total paid amount for out-of-network providers.',starter:"SELECT p.provider_name, SUM(c.paid_amount) AS spend\nFROM claims c JOIN providers p ON c.provider_id=p.provider_id\nWHERE p.network_status='Out of Network'\nGROUP BY p.provider_name;",hints:['Filter the provider dimension after joining it to claims.', 'SELECT p.provider_name, SUM(c.paid_amount) AS spend
FROM claims c JOIN providers p ON c.provider_id=p.provider_id
GROUP BY p.provider_name;', "SELECT p.provider_name, SUM(c.paid_amount) AS spend
FROM claims c JOIN providers p ON c.provider_id=p.provider_id
WHERE p.network_status='Out of Network'
GROUP BY p.provider_name;"],explanation:'This combines a dimension attribute with a fact measure.',check:r=>r.length>=1&&'provider_name' in r[0]},
  {id:7,dataset:'contact',title:'Average Handle Time by Queue',difficulty:'Intermediate',topic:'Operations',prompt:'Return each queue and average handle time in minutes, highest first.',starter:'SELECT queue, AVG(handle_seconds)/60.0 AS avg_handle_minutes\nFROM calls\nGROUP BY queue\nORDER BY avg_handle_minutes DESC;',hints:['Average handle_seconds, then convert seconds to minutes.', 'SELECT queue, AVG(handle_seconds) AS avg_handle_sec
FROM calls
GROUP BY queue;', 'SELECT queue, AVG(handle_seconds)/60.0 AS avg_handle_minutes
FROM calls
GROUP BY queue
ORDER BY avg_handle_minutes DESC;'],explanation:'AHT is a core contact-center operational metric.',check:r=>r.length>=3&&'avg_handle_minutes' in r[0]},
  {id:8,dataset:'contact',title:'Abandonment Rate',difficulty:'Hard',topic:'KPI',prompt:'Calculate overall abandonment rate as abandoned calls divided by all calls.',starter:'SELECT SUM(CASE WHEN abandoned THEN 1 ELSE 0 END)::DOUBLE / COUNT(*) AS abandonment_rate\nFROM calls;',hints:['Build numerator and denominator at the same grain.', 'SELECT SUM(CASE WHEN abandoned THEN 1 ELSE 0 END) AS abandoned_calls, COUNT(*) AS total_calls FROM calls;', 'SELECT SUM(CASE WHEN abandoned THEN 1 ELSE 0 END)::DOUBLE / COUNT(*) AS abandonment_rate
FROM calls;'],explanation:'KPI SQL is about a precise numerator, denominator and population.',check:r=>r.length===1&&'abandonment_rate' in r[0]},
  {id:9,dataset:'streaming',title:'Minutes by Subscriber',difficulty:'Beginner',topic:'SUM',prompt:'Return subscriber_id and total minutes watched, highest first.',starter:'SELECT subscriber_id, SUM(minutes) AS total_minutes\nFROM viewing\nGROUP BY subscriber_id\nORDER BY total_minutes DESC;',hints:['Viewing is event-level; aggregate minutes by subscriber.', 'SELECT subscriber_id, SUM(minutes) AS total_minutes
FROM viewing
GROUP BY subscriber_id;', 'SELECT subscriber_id, SUM(minutes) AS total_minutes
FROM viewing
GROUP BY subscriber_id
ORDER BY total_minutes DESC;'],explanation:'This is the first step toward engagement and retention analysis.',check:r=>r.length>=5&&'total_minutes' in r[0]},
  {id:10,dataset:'streaming',title:'Premium Engagement',difficulty:'Hard',topic:'JOIN',prompt:'Return premium subscribers and their total viewing minutes, including premium subscribers with zero views.',starter:"SELECT s.subscriber_id, COALESCE(SUM(v.minutes),0) AS total_minutes\nFROM subscribers s LEFT JOIN viewing v ON s.subscriber_id=v.subscriber_id\nWHERE s.plan='Premium'\nGROUP BY s.subscriber_id\nORDER BY total_minutes DESC;",hints:['Use LEFT JOIN to preserve subscribers with no viewing events.', 'SELECT s.subscriber_id, s.plan FROM subscribers s LEFT JOIN viewing v ON s.subscriber_id=v.subscriber_id WHERE s.plan='Premium';', "SELECT s.subscriber_id, COALESCE(SUM(v.minutes),0) AS total_minutes
FROM subscribers s LEFT JOIN viewing v ON s.subscriber_id=v.subscriber_id
WHERE s.plan='Premium'
GROUP BY s.subscriber_id
ORDER BY total_minutes DESC;"],explanation:'The preservation requirement determines the join type.',check:r=>r.length===4&&'total_minutes' in r[0]},
];

export const projects: Project[] = [
  {id:'pharmacy',title:'Pharmacy Spend Investigation',icon:'🏥',dataset:'healthcare',difficulty:'Senior Analyst',business:'Pharmacy spend increased 14% month over month. Leadership wants to know what is driving the increase before the next utilization review.',stakeholder:'VP, Pharmacy Operations',outcome:'Identify the spend drivers, quantify concentration, and recommend the next investigation.',tasks:[
    {id:1,title:'Establish the baseline',prompt:'Return total paid spend and claim count by month.',starter:"SELECT DATE_TRUNC('month', claim_date) AS month, SUM(paid_amount) AS spend, COUNT(*) AS claims FROM claims GROUP BY 1 ORDER BY 1;",check:r=>r.length>=2&&'spend' in r[0]},
    {id:2,title:'Find the biggest drug drivers',prompt:'Rank drugs by total paid spend.',starter:'SELECT drug, SUM(paid_amount) AS spend FROM claims GROUP BY 1 ORDER BY spend DESC;',check:r=>r.length>=3&&'spend' in r[0]},
    {id:3,title:'Check provider concentration',prompt:'Join providers and calculate paid spend by provider and network status.',starter:'SELECT p.provider_name, p.network_status, SUM(c.paid_amount) AS spend FROM claims c JOIN providers p ON p.provider_id=c.provider_id GROUP BY 1,2 ORDER BY spend DESC;',check:r=>r.length>=3&&'provider_name' in r[0]},
  ]},
  {id:'contact',title:'Contact Center SLA Diagnosis',icon:'📞',dataset:'contact',difficulty:'Senior Analyst',business:'The operations team believes queue performance is deteriorating. Diagnose AHT, wait time, abandonment and resolution patterns.',stakeholder:'Director, Customer Operations',outcome:'Identify the queues or teams that need operational intervention.',tasks:[
    {id:1,title:'Measure queue health',prompt:'Return calls, average handle time and average wait time by queue.',starter:'SELECT queue, COUNT(*) AS calls, AVG(handle_seconds)/60.0 AS avg_aht_min, AVG(wait_seconds) AS avg_wait_sec FROM calls GROUP BY 1 ORDER BY avg_wait_sec DESC;',check:r=>r.length>=3&&'avg_aht_min' in r[0]},
    {id:2,title:'Calculate abandonment',prompt:'Calculate abandonment rate by queue.',starter:'SELECT queue, SUM(CASE WHEN abandoned THEN 1 ELSE 0 END)::DOUBLE/COUNT(*) AS abandonment_rate FROM calls GROUP BY 1 ORDER BY abandonment_rate DESC;',check:r=>r.length>=3&&'abandonment_rate' in r[0]},
    {id:3,title:'Compare agents',prompt:'Join agents and compare call volume and average handle time by agent.',starter:'SELECT a.agent_name, a.team, COUNT(*) AS calls, AVG(c.handle_seconds)/60.0 AS avg_aht_min FROM calls c JOIN agents a ON a.agent_id=c.agent_id GROUP BY 1,2 ORDER BY calls DESC;',check:r=>r.length>=5&&'agent_name' in r[0]},
  ]},
  {id:'ecommerce',title:'E-commerce Revenue Drop',icon:'🛒',dataset:'commerce',difficulty:'Advanced',business:'Revenue is below plan. Diagnose whether the issue is customer concentration, product mix, or channel performance.',stakeholder:'Head of Growth',outcome:'Produce an evidence-backed revenue diagnosis and identify the highest-priority follow-up.',tasks:[
    {id:1,title:'Build revenue by channel',prompt:'Return channel revenue and order count.',starter:'SELECT channel, SUM(amount) AS revenue, COUNT(*) AS orders FROM orders GROUP BY 1 ORDER BY revenue DESC;',check:r=>r.length>=3&&'revenue' in r[0]},
    {id:2,title:'Rank products',prompt:'Join products and rank categories by revenue.',starter:'SELECT p.category, SUM(o.amount) AS revenue FROM orders o JOIN products p ON p.product_id=o.product_id GROUP BY 1 ORDER BY revenue DESC;',check:r=>r.length>=2&&'category' in r[0]},
    {id:3,title:'Find customer concentration',prompt:'Return the top five customers by lifetime order revenue.',starter:'SELECT c.customer_id,c.name,SUM(o.amount) AS revenue FROM customers c JOIN orders o ON o.customer_id=c.customer_id GROUP BY 1,2 ORDER BY revenue DESC LIMIT 5;',check:r=>r.length>=3&&'revenue' in r[0]},
  ]},
  {id:'streaming',title:'Streaming Retention Investigation',icon:'🎬',dataset:'streaming',difficulty:'Advanced',business:'Engagement is falling for newer subscribers. Use signup cohorts and viewing activity to identify where retention risk is concentrated.',stakeholder:'Director, Subscriber Growth',outcome:'Separate acquisition mix from engagement behavior and identify at-risk cohorts.',tasks:[
    {id:1,title:'Build subscriber cohorts',prompt:'Count subscribers by signup month.',starter:"SELECT DATE_TRUNC('month', signup_date) AS cohort_month, COUNT(*) AS subscribers FROM subscribers GROUP BY 1 ORDER BY 1;",check:r=>r.length>=3&&'subscribers' in r[0]},
    {id:2,title:'Measure engagement',prompt:'Return total viewing minutes by subscriber.',starter:'SELECT subscriber_id, SUM(minutes) AS minutes_watched FROM viewing GROUP BY 1 ORDER BY minutes_watched DESC;',check:r=>r.length>=5&&'minutes_watched' in r[0]},
    {id:3,title:'Find low-engagement subscribers',prompt:'Return subscribers with no viewing or less than 60 minutes watched.',starter:'SELECT s.subscriber_id, s.plan, COALESCE(SUM(v.minutes),0) AS minutes_watched FROM subscribers s LEFT JOIN viewing v ON v.subscriber_id=s.subscriber_id GROUP BY 1,2 HAVING COALESCE(SUM(v.minutes),0)<60 ORDER BY minutes_watched;',check:r=>r.length>=1&&'minutes_watched' in r[0]},
  ]},
];

export const interviews = [
  {difficulty:'Easy',title:'Customers with no orders',prompt:'Return every customer who has never placed an order.',answer:'SELECT c.* FROM customers c LEFT JOIN orders o ON c.customer_id=o.customer_id WHERE o.order_id IS NULL;',concept:'LEFT JOIN + NULL filtering',dataset:'commerce'},
  {difficulty:'Easy',title:'Monthly revenue',prompt:'Calculate monthly revenue in chronological order.',answer:"SELECT DATE_TRUNC('month',order_date) month,SUM(amount) revenue FROM orders GROUP BY 1 ORDER BY 1;",concept:'Date grain + aggregation',dataset:'commerce'},
  {difficulty:'Medium',title:'Top customer per city',prompt:'Return the highest-revenue customer in every city.',answer:'WITH r AS (SELECT c.city,c.name,SUM(o.amount) revenue FROM customers c JOIN orders o ON c.customer_id=o.customer_id GROUP BY 1,2), ranked AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY city ORDER BY revenue DESC) rn FROM r) SELECT city,name,revenue FROM ranked WHERE rn=1;',concept:'CTE + ROW_NUMBER',dataset:'commerce'},
  {difficulty:'Medium',title:'SLA rate by team',prompt:'Using the contact-center dataset, calculate resolved-call rate by queue.',answer:'SELECT queue,AVG(CASE WHEN resolved THEN 1.0 ELSE 0 END) resolution_rate FROM calls GROUP BY queue ORDER BY resolution_rate DESC;',concept:'CASE + KPI aggregation',dataset:'contact'},
  {difficulty:'Hard',title:'Drug spend by member segment',prompt:'Join claims to members and calculate spend by segment.',answer:'SELECT m.segment,SUM(c.paid_amount) spend FROM claims c JOIN members m ON c.member_id=m.member_id GROUP BY m.segment ORDER BY spend DESC;',concept:'Fact + dimension join',dataset:'healthcare'},
  {difficulty:'Hard',title:'Previous-month comparison',prompt:'Calculate monthly revenue and prior-month revenue using a window function.',answer:"WITH m AS (SELECT DATE_TRUNC('month',order_date) month,SUM(amount) revenue FROM orders GROUP BY 1) SELECT month,revenue,LAG(revenue) OVER(ORDER BY month) prior_month FROM m ORDER BY month;",concept:'CTE + LAG',dataset:'commerce'},
  {difficulty:'Senior',title:'Duplicate business keys',prompt:'Find duplicate customer IDs and count their occurrences.',answer:'SELECT customer_id,COUNT(*) occurrences FROM customers GROUP BY customer_id HAVING COUNT(*)>1;',concept:'Data-quality validation',dataset:'commerce'},
  {difficulty:'Senior',title:'90-day high-value cohort',prompt:'Describe a query that segments customers by recent order count and spend, then ranks segments by revenue.',answer:"WITH r AS (SELECT c.customer_id,c.name,COUNT(o.order_id) orders,SUM(o.amount) spend FROM customers c LEFT JOIN orders o ON c.customer_id=o.customer_id AND o.order_date>=DATE '2026-01-01' GROUP BY 1,2), s AS (SELECT *,CASE WHEN spend>=30000 AND orders>=2 THEN 'High Value' WHEN spend>=10000 THEN 'Core' ELSE 'Emerging' END segment FROM r) SELECT segment,COUNT(*) customers,SUM(spend) revenue FROM s GROUP BY segment ORDER BY revenue DESC;",concept:'Join filter placement + CASE + aggregation',dataset:'commerce'},
];

export const cases = [
  {id:'pharmacy',icon:'🏥',title:'Pharmacy Claims',difficulty:'Advanced',desc:'Healthcare spend increased 14%. Find the drivers by drug, member segment, provider and month.',dataset:'healthcare',kpis:['12 claims','8 members','6 providers','3 months'],questions:['Which drugs drive total paid spend?','How does spend differ by member segment?','Which providers have the highest spend?','What changed month over month?','Are out-of-network claims concentrated?']},
  {id:'contact',icon:'📞',title:'Contact Center SLA',difficulty:'Intermediate',desc:'Operations leadership says service levels deteriorated. Diagnose AHT, abandonment and resolution patterns.',dataset:'contact',kpis:['12 calls','6 agents','3 queues','2 days'],questions:['Which queues have the highest AHT?','Where is abandonment concentrated?','Which agents have unusual handle times?','What is the overall resolution rate?','What additional data would you request?']},
  {id:'commerce',icon:'🛒',title:'E-commerce Revenue',difficulty:'Advanced',desc:'Revenue is falling. Separate customer mix, channel, product and geographic effects.',dataset:'commerce',kpis:['8 customers','16 orders','5 products','4 cities'],questions:['Which cities drive revenue?','Which products drive revenue?','Which channel has the highest revenue?','Who are the highest-value customers?','What changed between months?']},
  {id:'streaming',icon:'🎬',title:'Streaming Retention',difficulty:'Intermediate',desc:'Leadership wants to understand engagement patterns associated with subscriber retention.',dataset:'streaming',kpis:['8 subscribers','11 views','2 plans','4 regions'],questions:['Which subscribers are most engaged?','How does Premium compare with Basic?','Which regions show stronger engagement?','Which subscribers have zero activity?','What retention data is missing?']},
];

export const schemas: Record<string,{name:string;description:string;columns:string[]}[]> = {
  commerce:[{name:'customers',description:'One row per customer',columns:['customer_id INTEGER','name VARCHAR','city VARCHAR','signup_date DATE','lifetime_value DOUBLE']},{name:'orders',description:'One row per order',columns:['order_id INTEGER','customer_id INTEGER','product_id INTEGER','order_date DATE','amount DOUBLE','channel VARCHAR']},{name:'products',description:'One row per product',columns:['product_id INTEGER','product_name VARCHAR','category VARCHAR','unit_price DOUBLE']}],
  healthcare:[{name:'members',description:'One row per member',columns:['member_id INTEGER','segment VARCHAR','state VARCHAR','age_band VARCHAR']},{name:'claims',description:'One row per pharmacy claim',columns:['claim_id INTEGER','member_id INTEGER','provider_id INTEGER','drug VARCHAR','claim_date DATE','paid_amount DOUBLE','status VARCHAR']},{name:'providers',description:'One row per provider',columns:['provider_id INTEGER','provider_name VARCHAR','specialty VARCHAR','network_status VARCHAR']}],
  contact:[{name:'agents',description:'One row per agent',columns:['agent_id INTEGER','agent_name VARCHAR','team VARCHAR']},{name:'calls',description:'One row per call',columns:['call_id INTEGER','agent_id INTEGER','call_date DATE','queue VARCHAR','handle_seconds INTEGER','wait_seconds INTEGER','resolved BOOLEAN','abandoned BOOLEAN']}],
  streaming:[{name:'subscribers',description:'One row per subscriber',columns:['subscriber_id INTEGER','plan VARCHAR','signup_date DATE','region VARCHAR']},{name:'viewing',description:'One row per viewing event',columns:['subscriber_id INTEGER','content_id INTEGER','view_date DATE','minutes INTEGER']}]
};
export const conceptDetails = {
  execution:{title:'Query execution order',icon:'⚙️',level:'Core mental model',summary:'SQL looks like a sentence, but the database reasons through the clauses in a different logical order. Understanding that order explains aliases, WHERE vs HAVING, and many “why does this query not work?” moments.',steps:['FROM / JOIN','WHERE','GROUP BY','HAVING','SELECT','ORDER BY','LIMIT'],example:`SELECT city, COUNT(*) AS customers\nFROM customers\nWHERE lifetime_value >= 25000\nGROUP BY city\nHAVING COUNT(*) >= 2\nORDER BY customers DESC\nLIMIT 3;`,why:'Imagine a funnel. First SQL finds the rows and joins tables. Then it filters rows, groups them, filters groups, creates the selected output, sorts it, and finally limits what you see.',mistakes:['Trying to use an aggregate in WHERE','Expecting a SELECT alias to exist during WHERE','Using HAVING for a simple row filter'],check:'If you need to remove individual rows before grouping, which clause should you use?',answer:'WHERE'},
  joins:{title:'JOINs: think in grains, not just keys',icon:'🔗',level:'Core mental model',summary:'A JOIN is a relationship between sets of rows. The key question is not “what column do I join on?” but “what does one row represent before and after the join?”',steps:['Customers: 1 row / customer','Orders: 1 row / order','Join key: customer_id','One customer → many orders','Rows can multiply','Validate the grain'],example:`SELECT c.customer_id, c.name, SUM(o.amount) AS revenue\nFROM customers c\nJOIN orders o\n  ON c.customer_id = o.customer_id\nGROUP BY c.customer_id, c.name;`,why:'If one customer has five orders, the customer row can match five order rows. That is expected for a one-to-many relationship. Problems happen when the relationship is unexpectedly many-to-many.',mistakes:['Joining on a non-unique column','Adding DISTINCT instead of fixing duplication','Aggregating after an accidental many-to-many join'],check:'If customers has 8 rows and orders has 16 rows, can a customer appear multiple times after joining?',answer:'Yes — one customer can match many orders.'},
  group:{title:'GROUP BY: changing the grain',icon:'📊',level:'Core mental model',summary:'GROUP BY is a grain-changing operation. Before it, you have detailed rows. After it, you have one row for every unique combination of grouped dimensions.',steps:['Detail rows','Choose dimensions','Choose measures','Aggregate','One row / group','Validate totals'],example:`SELECT city, COUNT(*) AS customers, AVG(lifetime_value) AS avg_ltv\nFROM customers\nGROUP BY city\nORDER BY customers DESC;`,why:'Think of a pile of receipts. GROUP BY city puts receipts into city buckets, then COUNT or SUM calculates something for each bucket. The output is no longer one row per receipt.',mistakes:['Selecting a column that is neither grouped nor aggregated','Grouping by too many columns','Forgetting that SUM(amount) changes the unit of analysis'],check:'If you GROUP BY city, what does one output row represent?',answer:'One city.'},
  windows:{title:'Window functions: calculate without collapsing',icon:'🪟',level:'Advanced mental model',summary:'Window functions let you look across related rows while keeping the original detail. This is the bridge between ordinary aggregation and advanced analyst SQL.',steps:['Keep every row','PARTITION BY group','ORDER BY sequence','Calculate window','Compare / rank','Filter in outer query'],example:`SELECT customer_id, order_date, amount,\n       ROW_NUMBER() OVER (\n         PARTITION BY customer_id\n         ORDER BY order_date\n       ) AS purchase_no\nFROM orders;`,why:'GROUP BY would collapse each customer into one row. ROW_NUMBER keeps every order and adds context about where that order sits inside the customer history.',mistakes:['Forgetting PARTITION BY','Using the wrong ORDER BY','Trying to filter a window alias in WHERE of the same query'],check:'Which tool would you use to keep every order but label the first, second and third order for each customer?',answer:'ROW_NUMBER() OVER (PARTITION BY customer_id ...)'},
  kpi:{title:'KPI construction: SQL starts with a definition',icon:'🎯',level:'Analyst thinking',summary:'A KPI is not just a formula. It defines a population, numerator, denominator, time window and grain. Good SQL makes those decisions visible and testable.',steps:['Population','Numerator','Denominator','Time window','Grain','Validation'],example:`SELECT\n  SUM(CASE WHEN resolved THEN 1 ELSE 0 END)::DOUBLE\n  / NULLIF(COUNT(*),0) AS resolution_rate\nFROM calls\nWHERE call_date >= DATE '2026-03-01';`,why:'Before coding “SLA rate,” ask: Which calls? Which period? What counts as resolved? Are abandoned calls included? Once those are clear, the SQL becomes much easier to trust.',mistakes:['Changing denominator without noticing','Mixing daily and monthly grains','Using COUNT(column) when NULLs should count'],check:'What should you define before writing a KPI formula?',answer:'Population, numerator, denominator, time window and grain.'},
  debug:{title:'JOIN debugging: prove where the rows changed',icon:'🧪',level:'Senior analyst skill',summary:'When a result looks too large, too small or duplicated, do not immediately add DISTINCT. Measure row counts at each stage and identify which relationship changed the grain.',steps:['Count table A','Count table B','Join','Count joined rows','Find duplicate keys','Fix relationship'],example:`SELECT customer_id, COUNT(*) AS rows_after_join\nFROM customers c\nJOIN orders o\n  ON c.customer_id = o.customer_id\nGROUP BY customer_id\nHAVING COUNT(*) > 1;`,why:'Unexpected duplication is usually a data-model problem. If the business expects one row per customer but your join produces five rows for a customer, you need to understand why before aggregating.',mistakes:['Using DISTINCT to hide duplication','Assuming every ID is unique','Ignoring row counts before and after joins'],check:'What should you inspect first when a join unexpectedly multiplies rows?',answer:'The grain and uniqueness of the join keys.'}
} as const;
