import { topics } from './curriculum';
import { sectionExamples, SectionExample } from './topic-examples';

export type StudioId = 'python'|'terminal'|'spark'|'dbt'|'config';
export type StudioLesson = {id:string;title:string;topicId:number;explanation:string;example:SectionExample;task:string;runnable:boolean};
export type Studio = {id:StudioId;title:string;description:string;environment:string;extension:string;lessons:StudioLesson[]};
export function normalizeStudioDraft(value:unknown,initialCode:string):{code:string;notes:string;studied:boolean} {
  const saved=value && typeof value==='object' && !Array.isArray(value)?value as Record<string,unknown>:{};
  return {code:typeof saved.code==='string'&&saved.code.length<=50000?saved.code:initialCode,notes:typeof saved.notes==='string'?saved.notes.slice(0,12000):'',studied:saved.studied===true};
}
export function lessonExtension(lesson:StudioLesson):string {
  const language=lesson.example.language;
  if(language.includes('PowerShell'))return 'ps1';
  if(language.includes('Bash'))return 'sh';
  if(language.includes('YAML'))return 'yml';
  if(language.includes('JSON'))return 'json';
  if(language.includes('SQL')||language.startsWith('dbt model'))return 'sql';
  if(language.includes('Python')||language.includes('PySpark'))return 'py';
  return 'txt';
}
function from(topicId:number,index:number,runnable=false):StudioLesson {
  const topic=topics.find(t=>t.id===topicId)!;
  return {id:`topic-${topicId}-${index}`,title:topic.sections[index][0],topicId,explanation:topic.sections[index][1],example:sectionExamples[topicId][index],task:topic.task,runnable};
}
function lesson(id:string,title:string,topicId:number,explanation:string,code:string,parts:[string,string][],expected:string,task:string,language='Python · browser runtime',runnable=true):StudioLesson {
  return {id,title,topicId,explanation,example:{scenario:explanation,language,code,parts,expected},task,runnable};
}
const pythonBasics = [
  lesson('py-values','Values, variables, and types',4,'Use a variable to name a value. Numbers support arithmetic; text needs parsing before arithmetic. Assignment binds a name to the result on its right.', 'amount = "20"\nquantity = 3\nrevenue = int(amount) * quantity\nprint(revenue)\nprint(type(revenue).__name__)',[['"20"','Text containing digits, not an integer yet.'],['int(amount)','Converts the text to an integer; invalid digits raise ValueError.'],['* quantity','Multiplies the parsed amount by 3.']],'Two lines: 60 and int.','Change quantity to 4 and predict the result. Then try amount = "unknown" and explain the error.'),
  lesson('py-collections','Lists and dictionaries',4,'A list stores an ordered sequence. A dictionary associates a key with a value. Choose a stable order ID as a key when you need to look up a particular record.', 'amounts = [10, 20, 5]\norder = {"id": 7, "amount": 20}\nprint(amounts[0])\nprint(order["amount"])\nprint(sum(amounts))',[['[0]','Reads the first list item: Python indexes start at zero.'],['["amount"]','Looks up the dictionary value by its key.'],['sum(amounts)','Adds the three numeric list values.']],'Three lines: 10, 20, and 35.','Append 15 to amounts and change the order amount to 25. Predict both affected outputs.'),
  lesson('py-control','Conditions and loops',4,'A for loop visits each item. An if statement selects which items contribute. Indentation defines the loop and condition bodies; the final print is outside both.', 'orders = [{"amount":10,"status":"paid"},{"amount":99,"status":"cancelled"},{"amount":20,"status":"paid"}]\nrevenue = 0\nfor order in orders:\n    if order["status"] == "paid":\n        revenue += order["amount"]\nprint(revenue)',[['for order in orders','Visits each of the three dictionaries.'],['== "paid"','Tests equality; it does not assign a status.'],['+=','Adds the amount to the existing total only for paid records.']],'30; the cancelled 99 is excluded.','Add a paid order for 7. Then make the condition include cancelled orders and compare totals.'),
  from(4,0,true),
  lesson('py-errors','Validation and exceptions',4,'Parsing can fail. Catch the specific conversion error, record a rejection, and keep accepted values separate. Silently replacing bad input with zero would hide a quality issue.', 'raw = ["10", "bad", "20"]\naccepted, rejected = [], []\nfor value in raw:\n    try:\n        accepted.append(int(value))\n    except ValueError:\n        rejected.append(value)\nprint(sum(accepted))\nprint(rejected)',[['try','Attempts integer conversion and appending.'],['except ValueError','Handles a conversion failure without hiding unrelated errors.'],['rejected','Retains the bad input for inspection.']],'Two lines: 30 and [\'bad\'].','Add another invalid string. Verify accepted + rejected counts equal the input count.'),
  lesson('py-csv','Read CSV without external files',4,'The csv module handles delimited records. StringIO makes this tiny fixture act like a text file so the example runs in the browser. CSV values arrive as strings and require explicit conversion.', 'import csv\nfrom io import StringIO\ntext = "id,amount\\n1,10\\n2,20\\n"\nrows = list(csv.DictReader(StringIO(text)))\nprint(sum(int(row["amount"]) for row in rows))',[['StringIO(text)','Provides a readable in-memory file.'],['DictReader','Uses the header to name dictionary keys.'],['int(row["amount"])','Converts each numeric string before summing.']],'30. No file on your computer is read.','Add a third CSV row, then try a non-numeric amount and add the previous lesson’s rejection handling.'),
  lesson('py-numpy','NumPy arrays',4,'NumPy performs array operations across compatible shapes. An array multiplied by 2 scales each element; a Python list multiplied by 2 repeats its sequence instead.', 'import numpy as np\namounts = np.array([10, 20, 5])\nprint((amounts * 2).tolist())\nprint(amounts[amounts >= 10].sum().item())',[['np.array','Constructs a numeric array.'],['amounts * 2','Multiplies every numeric element.'],['amounts >= 10','Creates a boolean selection mask before the sum.']],'Two lines: [20, 40, 10] and 30.','Compare [10, 20, 5] * 2 with the array result. Explain why they differ.'),
  from(4,2,true),from(9,1,true),from(13,2,true),from(17,1,true),from(18,2,true),from(20,0,true)
];
export const studios:Studio[] = [
  {id:'python',title:'Python Studio',description:'Start with Python fundamentals, then use NumPy, pandas, and pipeline exercises.',environment:'Runnable browser Python · NumPy and pandas supported · no Spark session or local computer files',extension:'py',lessons:pythonBasics},
  {id:'terminal',title:'Terminal & Git Studio',description:'Learn PowerShell, Bash, file paths, pipes, environments, and version control.',environment:'Guided practice · use a local PowerShell terminal, Bash/WSL, or a practice Git repository',extension:'txt',lessons:[from(1,0),from(1,1),from(1,2),from(4,1),
    lesson('bash-files','Bash paths and pipes',1,'In Bash or WSL, relative paths resolve from your current directory. This example assumes an existing practice/data folder and a notes.txt file with order grain and customer grain lines.', 'pwd\ncd ./data\ncat notes.txt | grep order',[['pwd','Displays the current directory.'],['cd ./data','Changes into the existing data child directory.'],['cat ... | grep order','Passes file contents to a filter that selects lines containing order.']],'The final command shows the order grain line. Bash commands differ from PowerShell cmdlets.','Create this fixture in a disposable directory; compare the Bash and PowerShell examples.','Bash · external terminal',false)]},
  {id:'spark',title:'PySpark Studio',description:'Read distributed DataFrame code, predict results, and practice transformations in Spark.',environment:'Guided practice · external PySpark installation or Databricks notebook with spark available',extension:'py',lessons:[from(10,0),
    lesson('spark-aggregate','Built-in aggregation and ordering',10,'Group rows at customer grain with built-in Spark functions. show is an action; orderBy makes the displayed sequence explicit.', 'from pyspark.sql import functions as F\ndf = spark.createDataFrame([(1,10),(1,20),(2,5)], "customer_id int, amount int")\nresult = df.groupBy("customer_id").agg(F.sum("amount").alias("revenue"))\nresult.orderBy("customer_id").show()',[['groupBy','Defines one aggregation group per customer ID.'],['F.sum + alias','Adds amounts in each group and names the result revenue.'],['orderBy + show','Orders and executes the displayed result.']],'Two rows: customer 1 → 30; customer 2 → 5. Requires an external Spark runtime.','Add another customer 2 order worth 7. Predict and verify its new revenue.','PySpark · external runtime',false),from(10,1),from(10,2),from(8,0),from(8,1)]},
  {id:'dbt',title:'dbt & Jinja Studio',description:'Understand templated models, source declarations, tests, and incremental reasoning.',environment:'Guided practice · requires a configured dbt project, adapter, and warehouse connection',extension:'txt',lessons:[from(12,0),
    lesson('dbt-source','Sources and Jinja compilation',12,'source declares a raw relation through your project’s source definition. dbt resolves its physical database/schema/table during compilation; braces are template syntax, not runnable SQL.', 'select order_id, customer_id, amount\nfrom {{ source("raw", "orders") }}',[['{{ ... }}','Evaluates a Jinja expression when dbt compiles the model.'],['source("raw", "orders")','Resolves a declared source and tracks its dependency.'],['select columns','Chooses the raw fields exposed by this staging model.']],'Compiled SQL refers to the relation configured for raw.orders. The project must declare that source first.','Declare a raw orders source in your practice project, compile, and inspect the generated relation name.','dbt SQL/Jinja · external project',false),
    lesson('dbt-tests','Declare key tests in YAML',12,'Place this model property declaration in a YAML file within your dbt model directory. The tests independently check that order_id is present and unique.', 'version: 2\nmodels:\n  - name: stg_orders\n    columns:\n      - name: order_id\n        data_tests:\n          - not_null\n          - unique',[['models / name','Identifies the existing stg_orders model.'],['columns / name','Selects its order_id column.'],['data_tests','Declares separate null and duplicate checks.']],'A null ID fails not_null; a repeated ID fails unique. Passing these two tests does not establish freshness or correct revenue.','Introduce a duplicate in a synthetic staging fixture, run dbt test, and inspect the failing rows.','YAML · dbt model properties',false),from(12,1),from(12,2)]},
  {id:'config',title:'Configuration Studio',description:'Learn JSON, YAML, and environment variables used around pipelines.',environment:'Guided practice · syntax examples; validate with the parser and tooling used by your project',extension:'txt',lessons:[
    lesson('config-json','JSON objects, arrays, and types',6,'JSON represents structured data using objects and arrays. Field names and text use double quotes; numeric values and booleans are unquoted. JSON does not support comments.', '{\n  "dataset": "orders",\n  "batch_size": 100,\n  "enabled": true,\n  "required_columns": ["id", "amount"]\n}',[['Object keys','Name the four settings.'],['100 / true','Keep number and boolean types rather than text.'],['Array','Lists two required column names.']],'A JSON parser yields four fields: text, number, boolean, and an array of strings.','Change batch_size to "100" and explain the type difference. Try a trailing comma in a JSON validator.','JSON · configuration example',false),
    lesson('config-yaml','YAML nesting and lists',11,'Indentation represents hierarchy in YAML. Use spaces consistently and keep tabs out of indentation. This is an illustrative application configuration; it is not an Airflow DAG definition.', 'pipeline:\n  name: orders\n  retries: 2\n  tasks:\n    - extract\n    - validate\n    - publish',[['pipeline:','Contains a nested mapping.'],['retries: 2','Assigns an integer retry setting in this illustrative schema.'],['- extract','Adds a list item; indentation places it inside tasks.']],'The pipeline mapping contains a name, retry count, and a three-item task list. A consumer must define and validate the schema.','Add reconcile before publish. Explain why this list alone does not enforce task dependencies.','YAML · illustrative configuration',false),
    lesson('config-env','Read an environment setting',15,'Environment variables separate deployment settings from code. This example demonstrates a non-secret value in PowerShell. Real secrets need the project’s approved secret mechanism.', '$env:PIPELINE_ENV = "practice"\npython -c "import os; print(os.environ.get(\'PIPELINE_ENV\', \'local\'))"',[['$env:PIPELINE_ENV','Sets the variable for this shell and its child processes.'],['os.environ.get','Reads that variable inside the spawned Python process.'],['local fallback','Supplies a value if the setting is absent.']],'practice when run from the configured PowerShell session. A different session without the variable prints local.','Use a new practice terminal and compare the default. Keep passwords out of examples, commits, and logs.','PowerShell + Python · external terminal',false)]}
];
