export type SectionExample = { scenario:string; language:string; code:string; parts:[string,string][]; expected:string };
const e = (scenario:string,language:string,code:string,parts:[string,string][],expected:string):SectionExample => ({scenario,language,code,parts,expected});

// Small, bounded examples accompany each of the three explanation sections.
// Walkthroughs describe decisions; they are not commands for a cloud account.
export const sectionExamples: Record<number,SectionExample[]> = {
  1:[
    e('Suppose you are in D:\\practice and it contains a data folder.','PowerShell · local terminal','Get-Location\nSet-Location .\\data\nGet-Location', [['Get-Location','Shows your current directory; it does not change files.'],['.\\data','A relative path: find data inside the current directory.'],['Set-Location','Changes the directory used to resolve your next relative path.']], 'The final location is D:\\practice\\data. If that folder is missing, Set-Location fails; it does not create it.'),
    e('Suppose notes.txt contains two lines: order grain and customer grain.','PowerShell · local terminal','Get-Content notes.txt | Select-String "order"', [['Get-Content','Reads the file’s lines into the pipeline.'],['|','Passes those lines to the next command.'],['Select-String "order"','Finds lines containing order; it does not edit the file.']], 'Only the order grain line matches. The file still contains both original lines.'),
    e('In a new practice repository, you changed only notes.txt.','Git · local terminal','git diff\ngit add notes.txt\ngit commit -m "Explain order grain"', [['git diff','Shows unstaged changes so you can inspect what changed.'],['git add notes.txt','Stages that file’s changes for the next snapshot.'],['git commit','Saves staged changes locally with a message; it does not upload them.']], 'A local commit contains the staged note. Unstaged edits in other files are not included. Git identity must already be configured.')
  ],
  2:[
    e('An imaginary API is https://orders.example.test/orders. These addresses are illustrative.','Request walkthrough','DNS: orders.example.test → 192.0.2.10\nTCP: connect to port 443\nTLS: verify server and encrypt\nHTTP: GET /orders', [['DNS','Finds the address associated with a hostname.'],['TCP + port','Connects to the service listening at that address and port.'],['TLS then HTTP','Protects the connection; HTTP describes the resource you request.']], 'The HTTP request starts only after the preceding connection/security steps succeed. This is a trace, not a live address to call.'),
    e('An API temporarily limits your request rate.','HTTP response example','HTTP/1.1 429 Too Many Requests\nRetry-After: 5', [['429','The server is telling this client to slow down.'],['Retry-After: 5','In this example, wait at least five seconds before another attempt.'],['Bounded retry','Try the same page again within a finite retry budget; do not advance its cursor.']], 'The current page is retried after the wait. A retry that still fails is surfaced, rather than looping forever.'),
    e('Pages A, B, and C contain different records. The process crashes after saving B.','Checkpoint walkthrough','fetch A → save A → checkpoint B\nfetch B → save B → checkpoint C\ncrash → restart at C', [['save','Makes a page durable before declaring it processed.'],['checkpoint C','Records the next page to fetch, not a claim that C is already saved.'],['Replay window','If the crash happens before checkpoint C, fetch B again and deduplicate its records.']], 'No page is skipped. A repeated page cannot add duplicate logical records when writes use stable source keys.')
  ],
  3:[
    e('Three toy orders have amounts 10, 20, and 5; the last order is cancelled.','DuckDB SQL · self-contained',"WITH orders(city, amount, status) AS (VALUES ('Delhi',10,'paid'),('Delhi',20,'paid'),('Pune',5,'cancelled'))\nSELECT city, SUM(amount) AS revenue FROM orders\nWHERE status = 'paid' GROUP BY city HAVING SUM(amount) > 15;", [['WHERE','Keeps the two paid rows before calculating revenue.'],['GROUP BY city','Forms one group per city in the remaining input.'],['SUM + HAVING','Adds 10 + 20, then keeps groups whose total exceeds 15.']], 'One row: Delhi, revenue 30. The cancelled Pune row never contributes to the sum.'),
    e('Customer 1 has two orders. Customer 2 has none.','DuckDB SQL · self-contained','WITH customers(id) AS (VALUES (1),(2)), orders(customer_id,amount) AS (VALUES (1,10),(1,20))\nSELECT c.id, COALESCE(SUM(o.amount),0) AS revenue\nFROM customers c LEFT JOIN orders o ON c.id=o.customer_id\nGROUP BY c.id ORDER BY c.id;', [['LEFT JOIN','Produces two matched rows for customer 1 and one unmatched row for customer 2.'],['SUM(o.amount)','Adds order amounts at the customer result grain.'],['COALESCE(...,0)','Reports zero when the sum is NULL; this is an explicit reporting choice.']], 'Customer 1 → 30; customer 2 → 0. The output has one row per customer despite multiple order rows.'),
    e('Two orders share a date, so order_id breaks the tie.','DuckDB SQL · self-contained',"WITH orders(id, day, amount) AS (VALUES (1,DATE '2026-01-01',10),(2,DATE '2026-01-01',20),(3,DATE '2026-01-02',5))\nSELECT id, SUM(amount) OVER (ORDER BY day,id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total\nFROM orders ORDER BY day,id;", [['OVER','Calculates across a window without collapsing the three orders into one row.'],['ORDER BY day,id','Defines a deterministic sequence even when dates match.'],['ROWS ... CURRENT ROW','Includes all preceding rows and the current one.']], 'Running totals are 10, 30, and 35 in order_id sequence. Each original order still has its own output row.')
  ],
  4:[
    e('A small function doubles one input number.','Python · standard library','def double(amount):\n    return amount * 2\n\nprint(double(20))', [['def','Defines a reusable function named double.'],['amount','The parameter receiving 20 when the function is called.'],['return + print','return sends 40 back to the caller; print displays that returned value.']], 'The printed result is 40. Defining the function alone does not run its body.'),
    e('Keep a project’s packages separate from other Python projects.','PowerShell · local environment','py -3 -m venv .venv\n.venv\\Scripts\\python -m pip install pandas numpy\n.venv\\Scripts\\python analysis.py', [['-m venv .venv','Creates a virtual environment directory using the chosen Python 3 interpreter.'],['environment python -m pip','Installs packages into that environment, not whichever pip happens to be on PATH.'],['analysis.py','Runs your saved script with the same environment’s interpreter.']], 'The script can import the environment’s installed pandas/NumPy packages. The commands require Python installed and a saved analysis.py file.'),
    e('Two paid orders belong to different cities; one cancelled order is excluded.','Python · requires pandas','import pandas as pd\ndf = pd.DataFrame({"city":["Delhi","Delhi","Pune"], "amount":[10,99,20], "status":["paid","cancelled","paid"]})\npaid = df.loc[df["status"].eq("paid")]\nprint(paid.groupby("city")["amount"].sum().to_dict())', [['.eq("paid")','Builds a True/False mask for the status column.'],['.loc[mask]','Keeps only rows where the mask is True.'],['groupby(...).sum()','Groups the kept rows by city and adds amounts within each group.']], 'The resulting dictionary is {Delhi: 10, Pune: 20}. The 99 cancelled amount is excluded. NumPy array arithmetic similarly operates on whole compatible arrays; np.array([10,20]) * 2 produces [20,40].')
  ],
  5:[
    e('One order contains two different products.','Modeling walkthrough','order 7, line 1, product A, line_amount 20\norder 7, line 2, product B, line_amount 30\nkey = (order_id, line_id)', [['Grain','One row describes one order line, not one whole order.'],['Composite key','The pair (7,1) differs from (7,2), so both rows can coexist.'],['Measure','Summing line_amount gives the order’s 50 total without repeating an order-level amount.']], 'Two fact rows, one order, revenue 50. order_id alone cannot uniquely identify an order-line row.'),
    e('Product A appears in thousands of order lines.','Star-schema walkthrough','fact_line: order_id, line_id, product_key, amount\ndim_product: product_key, category\nfact_line.product_key → dim_product.product_key', [['Fact','Stores events and amounts at the chosen grain.'],['Dimension','Stores the product description once per modeled product/version.'],['Key join','Attaches the matching description to each event without inventing additional purchases.']], 'Analysts can group line revenue by category. A snowflaked design could move category attributes into another dimension; that adds a relationship, not extra sales.'),
    e('A customer moved cities on February 1; January reports must preserve the old city.','History walkthrough','customer 8: Delhi, [Jan 1, Feb 1)\ncustomer 8: Pune,  [Feb 1, next change)\norder on Jan 20 → Delhi version', [['Type 1','Would overwrite Delhi with Pune, changing the descriptive view of past orders.'],['Type 2','Keeps a new row for the new city with an effective interval.'],['Event-time join','Selects the dimension version effective when the order happened.']], 'The January 20 order belongs to Delhi and the February 10 order to Pune. The half-open interval includes its start and excludes its end, avoiding a double match at midnight February 1.')
  ],
  6:[
    e('A raw order file is stored as an object rather than on your laptop.','Storage walkthrough','bucket: practice-orders\nkey: raw/orders/date=2026-01-01/run=001/orders.json\nregion: chosen to match processing requirements', [['Bucket/container','A named storage boundary containing objects.'],['Object key','The full identifier used to retrieve this file; slashes organize prefixes.'],['Region','The geographical placement of the resource, affecting residency and movement choices.']], 'An ingestion run can identify its exact input object. CSV stores text values; JSON can represent nested records; Parquet stores typed columns for column-oriented access.'),
    e('A transform service needs raw read access but analysts should not edit raw files.','Access walkthrough','transform: raw read, curated write\nanalyst: curated read\nanalyst request: raw write → denied', [['IAM','Associates identities with allowed actions and resources.'],['Least privilege','Gives each identity only the permissions its job needs.'],['Private endpoint','Restricts network reachability; it does not grant these permissions.']], 'A reachable analyst connection still cannot write raw objects. TLS protects network traffic; encryption at rest protects stored data under the provider/key configuration.'),
    e('A landing file has 100 source records and a checksum.','Manifest walkthrough','object_key: raw/orders/run=001/orders.json\nrow_count: 100\nchecksum: recorded-content-hash\nschema_version: 1', [['Immutable object','A new run gets a new identity rather than silently replacing the old input.'],['Checksum','Allows comparison of file contents to detect a changed input.'],['Manifest','Records which source object and schema version belong to the run.']], 'A replay can select the exact original input. Retention decides how long that object remains available; a budget alert warns about spending but may not stop resources.')
  ],
  7:[
    e('Two teams query the same governed tables with separate compute.','Warehouse walkthrough','stored sales table → finance compute → finance query\nstored sales table → analyst compute → analyst query', [['Storage','Persists data independently of a particular query session.'],['Compute','Executes scanning, joining, and aggregation work.'],['Isolation','Separate compute configurations can reduce workload interference where the platform supports it.']], 'The same logical table can serve multiple workloads. Snowflake virtual warehouses, BigQuery compute/pricing models, and Databricks SQL warehouses expose different controls, not identical billing units.'),
    e('Ask for January totals instead of every column and every month.','DuckDB SQL · self-contained',"WITH sales(day,amount) AS (VALUES (DATE '2026-01-02',10),(DATE '2026-02-02',20))\nSELECT SUM(amount) AS revenue FROM sales\nWHERE day >= DATE '2026-01-01' AND day < DATE '2026-02-01';", [['SELECT SUM(amount)','Requests one revenue value rather than every source column.'],['Date bounds','Select a half-open January interval that excludes February.'],['Physical layout','In a real warehouse, compatible date partitioning/clustering may reduce scanned data; this tiny VALUES example only demonstrates correctness.']], 'Revenue is 10. The result demonstrates filtering, not measured cloud cost savings.'),
    e('An unchanged query runs much faster the second time.','Measurement walkthrough','run A: cold cache, 10 seconds\nrun B: warm cache, 1 second\nquery and data: unchanged', [['Cache','Reuses previously computed or read information when supported.'],['Comparable conditions','A fair optimization comparison controls snapshot, compute, concurrency, and cache conditions.'],['Native units','Record the platform’s actual credits/bytes/compute time instead of inventing a universal price.']], 'The 10× timing difference alone does not prove an improved query. Repeat comparable trials and check equal outputs before claiming an optimization.')
  ],
  8:[
    e('A notebook cell reads a variable created in an earlier cell.','Notebook walkthrough','cell 1: source = "orders"\ncell 2: load(source)\nnew clean session: cell 2 alone → source is undefined', [['Cell state','Values can remain in memory from earlier executions.'],['Execution order','A visible cell layout does not guarantee those cells ran in that order.'],['Clean rerun','Restart and run in order to reveal missing setup and dependencies.']], 'The notebook is reproducible only when its documented setup and ordered execution succeed. This pseudocode illustrates state; load is not a provided function.'),
    e('Order 1 is already in silver with amount 100; one newer source record says 120.','Delta table walkthrough','bronze: keep both source versions\nsilver MERGE key=order_id: order 1 → amount 120\ngold daily total: recalculate from current silver records', [['Bronze','Keeps source-like records and metadata for replay.'],['MERGE','Matches by the declared key and applies the chosen update/insert rule.'],['Delta log','Records committed table changes; a table version is different from an independent backup.']], 'Silver contains one current logical order worth 120. The input must first be deduplicated; two conflicting incoming rows for one key are not an automatic safe update.'),
    e('Compare two forecast experiments on the same input table version.','Experiment walkthrough','run A: input version 12, horizon 7, error 8\nrun B: input version 12, horizon 14, error 11\nartifact: each run’s saved model', [['Parameter','An input choice such as forecast horizon.'],['Metric','A measured result such as validation error, with a stated definition.'],['Artifact + lineage','The saved model and the input dataset version needed to explain/reproduce the run.']], 'MLflow can organize the records for comparison. An error number is meaningful only with the same metric definition and validation method; never log sensitive training rows as public artifacts.')
  ],
  9:[
    e('An incoming order has an email field that should not reach an analyst table.','ETL/ELT walkthrough','ETL: source → remove restricted fields → destination\nELT: source → restricted raw destination → governed transformation → analyst table', [['Extract','Reads the source data.'],['Transform','Changes types, validates values, or applies a business/privacy rule.'],['Load','Writes to the chosen destination; its position differs between ETL and ELT.']], 'Both designs can produce a safe analyst table if access controls and retention are appropriate. ELT requires controlling who can access raw sensitive fields.'),
    e('The same purchase event arrives twice.','Python · standard library','events = [(1, 10), (2, 20), (1, 10)]\norders = {}\nfor key, amount in events:\n    orders[key] = amount\nprint(sum(orders.values()))', [['Dictionary key','Provides one current value per order ID in this bounded example.'],['Assignment','A repeat of key 1 replaces the same value instead of appending another purchase.'],['sum(values)','Adds the logical current values, not every arrival.']], 'The printed total is 30 rather than 40. This simple version handles identical replay; out-of-order updates require source-version precedence.'),
    e('Two changes for order 1 arrive out of order.','Version and schema walkthrough','arrival 1: order=1, source_version=3, amount=120\narrival 2: order=1, source_version=2, amount=100\naccept update only when version is newer', [['Source version','Defines change order independently of delivery time.'],['Version guard','Prevents an older arrival from overwriting a newer stored value.'],['Schema contract','Checks required key/type rules before applying the update.']], 'Order 1 remains 120 at version 3. A deletion tombstone also needs a version, so replaying an old live record cannot resurrect the order.')
  ],
  10:[
    e('A PySpark DataFrame holds three toy records.','PySpark · requires a Spark session named spark','df = spark.createDataFrame([(1,10),(1,20),(2,5)], "customer_id int, amount int")\nsmall = df.select("customer_id", "amount").filter("amount >= 10")\nsmall.show()', [['Schema','Names the columns and their intended data types.'],['select + filter','Describe a transformation plan; these operations do not by themselves display results.'],['show','An action that executes the work needed to display the bounded result.']], 'The displayed records are (1,10) and (1,20), with no guaranteed order unless you explicitly order them. This code needs an external Spark runtime.'),
    e('The same customer’s rows start in different partitions.','Shuffle walkthrough','partition A: customer 1 amount 10\npartition B: customer 1 amount 20\ngroupBy(customer_id).sum(amount)', [['Partition','A piece of the distributed input processed by a task.'],['Grouping key','Customer 1 must belong to one final aggregation group.'],['Shuffle','Moves or combines records across partition boundaries so grouped work can meet.']], 'Customer 1’s total is 30. Built-in aggregation lets Spark plan this work; an unnecessary Python UDF can add an extra execution boundary.'),
    e('A hot key owns most of the records.','Skew walkthrough','key A: 900,000 rows\nall other keys together: 100,000 rows\none task handling A finishes much later', [['Skew','Uneven work distribution rather than merely a large total input.'],['Task metrics','Help identify long-running tasks, shuffle volume, and spill.'],['Targeted change','Investigate key distribution and join strategy before blindly increasing partition count.']], 'Adding workers alone may leave the hot-key bottleneck. Measure a targeted mitigation and confirm the same logical output.')
  ],
  11:[
    e('A report depends on transformed data, which depends on validated input.','Dependency walkthrough','extract → validate → transform → reconcile → publish', [['Task','A unit of work with defined input/output behavior.'],['Dependency arrow','The next task waits for the required upstream success condition.'],['Orchestrator','Schedules and observes these units; it is not itself the storage or SQL engine.']], 'Failed validation prevents publication under this dependency policy. Airflow DAGs, Dagster assets, and Prefect flows represent related responsibilities with different APIs.'),
    e('The January 1 run is retried on January 3.','Task-contract walkthrough','run interval: [Jan 1 00:00, Jan 2 00:00)\ninput: raw/date=Jan-1\noutput: daily_revenue/date=Jan-1', [['Logical interval','Specifies the data the run is responsible for, independent of the wall-clock retry date.'],['Fixed input','Keeps a retry from accidentally reading January 3’s latest file.'],['Idempotent output','Allows the same logical interval to be written safely again.']], 'The retry repairs January 1 rather than generating a mislabeled January 3 report. Credentials belong in the configured secret/connection mechanism, not task code.'),
    e('Seven historical daily intervals need repair while current runs continue.','Backfill walkthrough','backfill: Jan 1 through Jan 7\nconcurrency limit: 2 intervals\nvalidation failure: block that interval’s publish', [['Backfill','Executes historical intervals through the normal transformation rules.'],['Concurrency limit','Caps simultaneous work to preserve capacity for other runs.'],['Failure policy','Retries transient issues but escalates a persistent data-contract violation.']], 'At most two backfill intervals run together in this example. A bad January 4 record is not fixed by endlessly retrying unchanged input.')
  ],
  12:[
    e('A revenue model consumes cleaned orders.','dbt model · requires a dbt project',"select customer_id, sum(amount) as revenue\nfrom {{ ref('stg_orders') }}\ngroup by customer_id", [['ref','Resolves the upstream dbt model and declares a dependency.'],['stg_orders','A staging model that standardizes source types/names before this mart uses them.'],['group by','Produces one customer revenue row per customer ID.']], 'If stg_orders has amounts 10 and 20 for customer 1, the model returns customer 1 → 30. Plain DuckDB does not understand Jinja braces; dbt compiles them first.'),
    e('One row has an invalid negative amount under this example’s no-refunds contract.','DuckDB SQL · self-contained','WITH orders(id,amount) AS (VALUES (1,10),(2,-5))\nSELECT id,amount FROM orders WHERE amount < 0;', [['Test query','Selects violating records, not passing records.'],['WHERE amount < 0','Expresses this example’s agreed invalid-value rule.'],['Test result','A non-empty violation result means the check fails.']], 'The failing row is (2,-5). If valid refunds may be negative, change the business contract/check rather than declaring every refund bad.'),
    e('An order created in January changes in March.','Incremental walkthrough','created_at: Jan 10\nupdated_at: Mar 2\nMarch load filter: updated_at in recent interval + overlap', [['Creation time','Indicates original creation, not later modifications.'],['Update time','Lets changed older records enter the incremental input.'],['Impact recalculation','Updates or rebuilds affected outputs at their true grain.']], 'The correction reaches March’s incremental processing even though the order was created in January. Aggregated customer revenue may need recomputing after replacing the order value.')
  ],
  13:[
    e('There are duplicate IDs, a missing key, and an out-of-range amount.','Quality contract walkthrough','required key: never NULL\ncurrent key: unique\namount: nonnegative under this contract\nfreshness: latest source interval must be present', [['Completeness','Checks required fields are present.'],['Uniqueness + validity','Check repeated keys and business/type rules.'],['Freshness','Checks recency independently of the value-level rules.']], 'A feed can pass all row-level checks yet fail freshness because the entire new file is missing. Each rule needs its own population, severity, and owner.'),
    e('Order 7 occurs twice in a small source.','DuckDB SQL · self-contained','WITH orders(id) AS (VALUES (7),(7),(8))\nSELECT id, COUNT(*) AS occurrences\nFROM orders GROUP BY id HAVING COUNT(*) > 1;', [['GROUP BY id','Collects all rows with the same order ID.'],['COUNT(*)','Counts occurrences of each ID.'],['HAVING > 1','Returns only IDs violating uniqueness.']], 'One violation row: id 7, occurrences 2. Zero violations is useful only if the input feed itself has the expected population.'),
    e('100 records were ingested; 94 were accepted and 5 quarantined.','Python · standard library','ingested, accepted, rejected = 100, 94, 5\nunexplained = ingested - accepted - rejected\nprint(unexplained)', [['Accepted','Records allowed into the modeled output under the contract.'],['Rejected','Records retained with a reason for investigation rather than silently discarded.'],['Reconciliation','Accounts for the entire input population.']], 'The printed unexplained count is 1. Investigate that missing disposition before publishing if the contract requires exact reconciliation.')
  ],
  14:[
    e('An event happened at 10:00 and was published at 10:07. The job itself took two minutes.','Latency walkthrough','event_time: 10:00\njob_start: 10:05\npublished_at: 10:07', [['Job duration','Measures job_start → published_at: two minutes here.'],['End-to-end latency','Measures event_time → published_at: seven minutes here.'],['Freshness target','If the agreed target is five minutes, this event misses it despite a fast job.']], 'A two-minute successful run does not prove five-minute freshness. Include scheduling/ingestion delay in the consumer-facing measurement.'),
    e('A green job processed only 10 rows instead of its expected input count of 100.','Signal walkthrough','run_id: orders-001\nexpected_input_rows: 100\nobserved_input_rows: 10\njob_exit_status: success', [['Run ID','Lets you connect log messages, manifests, and outputs for this run.'],['Count signal','Reveals a 90-record discrepancy that process status alone misses.'],['Contextual alert','Names the interval, owner, impact, and runbook instead of sending an unexplained failure ping.']], 'Investigate source completeness and filter/schema changes. This is a data-health problem even if the process exited successfully.'),
    e('A partial source file caused an incomplete daily report.','Runbook walkthrough','confirm source gap → stop unvalidated publish\nnotify affected consumers → repair input\nreplay fixed interval → reconcile → publish', [['Confirm','Separates a real incident from an incorrect alert.'],['Replay','Reprocesses a specific repaired interval through safe writes.'],['Reconcile before publish','Checks recovery correctness before replacing visible data.']], 'Consumers receive validated corrected data plus an accurate freshness notice. The runbook also records how to restore last-good output if correction takes time.')
  ],
  15:[
    e('A dashboard needs revenue by region, not customer emails.','Data-minimization walkthrough','raw: customer_id, email, region, amount\nanalyst mart: region, revenue\nrestricted field: email', [['PII classification','Identifies email as potentially identifying information needing appropriate controls.'],['Minimization','Avoids exposing or retaining fields unnecessary for the use case.'],['Aggregation','Can reduce detail exposed to the consumer, while still needing re-identification risk review where relevant.']], 'The analyst uses region revenue without receiving raw emails. Hashing an email alone does not prove the data is anonymous.'),
    e('The analyst needs read access to one mart; the transform service needs write access.','Authorization walkthrough','analyst → SELECT region_revenue\ntransform → write region_revenue\nanalyst → write region_revenue: denied', [['Role','Groups permissions for a defined responsibility.'],['Least privilege','Restricts actions/resources to what the responsibility needs.'],['Encryption + secret handling','Protect communication/storage and credentials separately from permission decisions.']], 'The analyst cannot modify the data just because they can view it. A service credential is stored outside source code and its access is audited.'),
    e('A deleted customer exists in raw files, silver records, and a derived export.','Governance walkthrough','raw → silver → export\ndelete request/policy → identify all relevant copies\nreplay rules → do not recreate removed records', [['Lineage','Traces which outputs depend on a source record.'],['Retention/deletion policy','Defines handling across live copies, raw replay inputs, and backups.'],['Audit trail','Records who performed relevant access or changes, without becoming a new uncontrolled sensitive-data copy.']], 'Deleting just the silver row may be insufficient. Apply the actual organization’s retention/deletion obligations and ensure later replay cannot undo the intended deletion.')
  ],
  16:[
    e('Two paid orders and one cancelled order enter a small batch.','Batch walkthrough','raw CSV: paid 10, paid 20, cancelled 99\nvalidate → keyed current orders table\nreport: SUM(amount) where status = paid', [['Raw input','Preserves the source records for reproduction and debugging.'],['Validated storage','Contains records meeting required key/type/status rules.'],['Report rule','Defines paid revenue rather than total money mentioned in every arrival.']], 'Paid revenue is 30, not 129. The source file and reporting rule let another person reproduce the calculation.'),
    e('Order 1 is corrected from 100 to 120 in a later source version.','Update walkthrough','version 1: order 1, amount 100\nversion 2: order 1, amount 120\ncurrent state: retain version 2', [['Key','Identifies which logical order an arrival changes.'],['Version precedence','Chooses the authoritative newer source value.'],['Transactional load','Commits a set of database changes together instead of exposing partially applied updates.']], 'The current order contributes 120. It does not contribute 220. A transaction in the local database does not automatically make a separate report-file write part of the same transaction.'),
    e('The downloadable batch starter validates a synthetic fixture before you extend it.','Local command walkthrough','python batch_pipeline.py --self-test\npython batch_pipeline.py --input orders.csv --output output', [['--self-test','Runs the built-in fixture/replay/failure checks in a temporary directory.'],['--input','Selects the CSV file you intend to load.'],['--output','Selects the directory for the SQLite database, revenue report, rejects, and manifest.']], 'The supplied fixture yields Jan 1 revenue 120, Jan 2 revenue 80, and one rejected input. These are local teaching results, not proof of cloud deployment.')
  ],
  17:[
    e('A purchase happened at 09:59 but arrived at 10:03.','Event-time walkthrough','event_time: 09:59\narrival_time: 10:03\npartition_key: customer 2', [['Event time','Assigns the event to when the business action happened.'],['Arrival/processing time','Shows when the system received/handled it.'],['Partition key','Influences which ordered partition/shard receives related events; it does not create global ordering.']], 'For an event-time minute report, this event belongs to 09:59. A processing-time report would answer a different question.'),
    e('The same event e1 is delivered twice around a restart.','Python · standard library','events = [("e1",20),("e2",30),("e1",20),("e3",10)]\nseen = {}\nfor event_id, amount in events:\n    seen[event_id] = amount\nprint(sum(seen.values()))', [['Event ID','Identifies a logical occurrence, distinguishing repeat delivery from a new event.'],['Deduplication state','Stores which logical events have already contributed.'],['Replay','Re-delivers events so state/output must tolerate repeats.']], 'The printed total is 60, not the raw arrival total of 80. This bounded dictionary is a logic illustration, not a durable exactly-once streaming deployment.'),
    e('Start with the local simulation before paying for external infrastructure.','Streaming architecture walkthrough','local fixture → duplicate/late-event rules → restart check\nexternal extension: Kafka or Kinesis → Spark → Delta silver/gold', [['Simulation','Tests logical behavior with a bounded known fixture.'],['Broker + checkpoint','External delivery and progress mechanisms whose recovery contract must be configured.'],['Sink','Publishes output; its write behavior must cooperate with retries and source progress.']], 'Passing the local simulator proves the fixture logic only. The deployed extension must separately measure latency and demonstrate recovery with its actual connector/runtime versions.')
  ],
  18:[
    e('A pipeline already works, but there is no clear evidence of health or performance.','Baseline walkthrough','fixture: fixed version\nrecord: rows, rejects, freshness, runtime\nchecks: keys + source reconciliation', [['Baseline','A reproducible starting point against which a change can be assessed.'],['Quality gate','Blocks publication when critical agreed checks fail.'],['Measured unit','Separates elapsed time, memory, and billed cost instead of treating them as interchangeable.']], 'You now have a record of correct outputs and comparable conditions before attempting optimization. Actual values must come from your run.'),
    e('Intentionally send a file missing its order_id column.','Failure walkthrough','input: amount,status\nrequired key: order_id\nvalidation → fail → publish blocked', [['Failure injection','Creates a known fault to test recovery rather than waiting for an accidental incident.'],['Schema validation','Checks required fields before attempting business aggregation.'],['Publication boundary','Keeps an incomplete/untrusted new report from becoming the visible result.']], 'The missing-key input fails clearly. Last-good publication remains available under the tested publication policy, and the runbook explains correction/replay.'),
    e('Toy timings illustrate how to report one measured change.','Python · standard library','from statistics import median\nbefore = [10, 11, 9]\nafter = [7, 8, 6]\nprint(median(before), median(after))\nprint((median(before)-median(after))/median(before)*100)', [['Median','A middle timing less sensitive than a single trial to one unusually slow run.'],['Same conditions','The example assumes equal data, outputs, compute, and cache conditions.'],['Percentage','Uses the baseline as the denominator.']], 'Toy medians are 10 and 7; the toy runtime reduction is 30%. These invented demonstration numbers are not your project results and do not establish cloud cost savings.')
  ],
  19:[
    e('A stranger opens the repository without knowing your environment.','README excerpt','# Orders practice pipeline\nRequires: Python 3, standard library\nRun: python batch_pipeline.py --self-test\nExpected: replay and validation checks pass', [['Prerequisites','Tell the reader what needs to exist before commands can work.'],['Run command','Makes the demonstration executable rather than merely descriptive.'],['Expected result','Lets the reader tell success from a plausible-looking but incorrect output.']], 'The reader can run one bounded verification step. Add the exact tested version and input/report commands from your own run.'),
    e('A simple diagram matches a local orders pipeline.','Architecture walkthrough','CSV → validation → SQLite orders → daily CSV report\n           ↓ rejected records\n          quarantine', [['Arrow','Shows a real data/dependency flow, not a decorative technology association.'],['Validation boundary','Decides which input records may become modeled data.'],['Quarantine branch','Keeps failed-record reasons available for reconciliation and repair.']], 'The diagram explains both successful processing and rejected input. Do not draw Kafka or a cloud warehouse if you did not implement them.'),
    e('A result page reports a replay test rather than an invented scale claim.','Evidence example','Input: supplied synthetic fixture\nAssertion: Jan 1 = 120; Jan 2 = 80\nSecond run: same sorted report\nLimit: local SQLite; no cloud throughput measurement', [['Assertion','States the value/behavior actually checked.'],['Reproduction','Links input, code version, command, and output.'],['Limitation','Keeps readers from mistaking the demo for unmeasured production capability.']], 'A reviewer can independently verify your correctness claim. This is stronger evidence than an unsupported “processed millions of records” bullet.')
  ],
  20:[
    e('A hypothetical feed contains one million events per day.','Python · standard library','events_per_day = 1_000_000\nseconds_per_day = 24 * 60 * 60\nprint(round(events_per_day / seconds_per_day, 2))', [['Units','Dividing events/day by seconds/day gives events/second.'],['Average','The result spreads events evenly across the day; real arrival peaks may be higher.'],['Requirements','Event size, peak factor, freshness, and durability must be clarified separately.']], 'The printed average is 11.57 events/second. It is not a peak-capacity requirement.'),
    e('Trace what happens if an output write fails after extraction.','Recovery walkthrough','source → durable raw → validate → transform → publish\noutput failure → keep checkpoint unchanged → replay raw interval', [['Durable landing','Preserves an input that can be read again.'],['Checkpoint','Declares completed progress only after its promised output is safe.'],['Idempotent write','Makes the replay produce the same logical result without duplicates.']], 'A restart can repair the failed interval. The design must state the storage/publication boundary rather than claiming checkpoints alone solve all failures.'),
    e('A consumer requests five-minute end-to-end freshness.','Tradeoff walkthrough','schedule wait: up to 5 minutes\nprocessing: 2 minutes\npossible total delay: 7 minutes', [['Waiting time','A new event may arrive just after the previous scheduled run.'],['Processing time','Adds to waiting and ingestion delay.'],['Alternative','Shorter micro-batches or streaming may meet the requirement; choose based on measured workload and operational constraints.']], 'A five-minute schedule can miss a five-minute freshness target. Name this tradeoff and validate the risky assumption before choosing a more complex design.')
  ],
  21:[
    e('Two rows tie for the largest amount.','DuckDB SQL · self-contained','WITH purchases(id,amount) AS (VALUES (1,30),(2,30),(3,10))\nSELECT id, ROW_NUMBER() OVER (ORDER BY amount DESC,id) AS rn,\nRANK() OVER (ORDER BY amount DESC) AS rnk,\nDENSE_RANK() OVER (ORDER BY amount DESC) AS dense_rnk\nFROM purchases ORDER BY id;', [['ROW_NUMBER','Assigns 1,2,3 with the ID tie-breaker, so filtering rn <= 1 picks exactly one row.'],['RANK','Assigns 1,1,3; the tie leaves a gap.'],['DENSE_RANK','Assigns 1,1,2; tied rows share rank without a gap.']], 'For IDs 1/2/3, ranks differ exactly as shown. Choose based on whether the question wants exactly N rows or all tied leaders.'),
    e('Activity occurred on days 1, 2, and 4; day 3 is missing.','DuckDB SQL · self-contained','WITH activity(day) AS (VALUES (1),(2),(4)), sequenced AS (\n SELECT day, ROW_NUMBER() OVER (ORDER BY day) AS n FROM activity\n) SELECT day, day-n AS island_key FROM sequenced ORDER BY day;', [['Deduplicated activity','This fixture already has one row per active day. Remove duplicates first in a real problem.'],['ROW_NUMBER','Counts observed days as 1,2,3.'],['day - n','Stays constant for consecutive integer days and changes after a gap.']], 'Days 1 and 2 get island key 0; day 4 gets key 1. Date-based versions need an appropriate date/interval operation and a defined timezone.'),
    e('January and March are present; February is missing.','DuckDB SQL · self-contained','WITH revenue(month,amount) AS (VALUES (1,100),(3,150))\nSELECT month, amount, LAG(amount) OVER (ORDER BY month) AS prior_observed\nFROM revenue ORDER BY month;', [['LAG','Reads the previous row in the stated window order.'],['Missing month','No February row exists for LAG to read.'],['Calendar spine','An explicit full month sequence lets you represent missing periods before deciding NULL versus zero.']], 'March’s prior_observed is January’s 100. Separately, if a signup cohort has 10 users and 4 qualifying active users, retention is 4/10 = 40%, not 4 divided by the number of events.')
  ],
  22:[
    e('Describe a practice project honestly.','Story example','Situation: my practice batch pipeline duplicated replayed orders.\nTask: make reruns safe.\nAction: keyed version updates + replay assertion.\nResult: same logical report on both runs.', [['Situation + task','Provide the context and your responsibility, including that it was practice work.'],['Action','Explains what you changed and why it addresses the fault.'],['Result','Gives observed verification instead of invented professional impact.']], 'The listener understands your own contribution and how you know it worked. Do not turn a personal exercise into fictional client employment.'),
    e('An order total was counted once per line item.','Root-cause story','Order total: 100\nJoined line rows: 3\nWrong sum: 300\nFix: aggregate at order grain before combining totals', [['Symptom','The reported revenue was unexpectedly large.'],['Root cause','A one-to-many join repeated the order measure.'],['Prevention','A grain assertion and tiny known fixture test catch the error.']], 'Your story explains 100 → 300 → corrected 100, plus the test that prevents recurrence. It does not merely say “I used SQL to fix data.”'),
    e('Rehearse a concise answer without stripping out proof.','Answer structure','20 sec: context and task\n60 sec: investigation and decisions\n25 sec: verified result\n15 sec: what I learned', [['Structure','Allocates time to the important reasoning rather than a long setup.'],['Evidence','Keeps a specific measurement/check in the result.'],['Reflection','Names a next improvement or changed habit.']], 'The example sums to two minutes. Treat the timing as a rehearsal aid, not a script or hiring guarantee.')
  ],
  23:[
    e('A target role asks for SQL, Python, orchestration, and cloud exposure.','Role-fit walkthrough','SQL: demonstrated queries and tests\nPython: completed batch lab\nOrchestration: design exercise only\nCloud: conceptual study only', [['Demonstrated','A claim backed by completed artifacts.'],['Design exposure','A separate category from operating a deployed system.'],['Targeting','Prioritizes relevant evidence without inflating weaker areas.']], 'Your profile can honestly emphasize SQL/Python and describe orchestration/cloud as study or planned extension rather than production mastery.'),
    e('Turn a vague skill claim into a reproducible project bullet.','Resume example','Before: Expert in big data and all cloud tools.\nAfter: Built a local Python/SQLite orders pipeline with versioned upserts, quarantine records, and replay checks on a synthetic fixture.', [['Action','Built identifies what you actually did.'],['System + scope','Local Python/SQLite and synthetic fixture specify the environment and limits.'],['Evidence','Upsert, quarantine, and replay checks identify behaviors a reviewer can inspect.']], 'The revised bullet is specific without inventing scale, savings, or employment experience.'),
    e('Your resume describes a local lab but LinkedIn calls it a production platform.','Consistency walkthrough','resume: personal local project\nLinkedIn: personal local project\nportfolio: same code, tested fixture, limits', [['Consistent context','All profiles distinguish personal work from employment.'],['Evidence link','Points to the repository/README supporting the claim.'],['Metric discipline','Only includes a number if you can explain its workload, baseline, and measurement.']], 'A reviewer sees the same truthful project story everywhere. Fix the “production” claim if no deployment/operational evidence exists.')
  ],
  24:[
    e('A timed practice session covers three kinds of explanation.','Session plan','SQL 15 min + design 10 min + story 5 min + review 5 min', [['SQL round','Write a query and explain grain, ties, NULLs, and tests.'],['Design/story rounds','Explain requirements/recovery and your real project contribution.'],['Review round','Records observed gaps rather than only whether you felt confident.']], 'The session lasts 35 minutes. Recording is optional; a timer and written review log are enough.'),
    e('A query is correct but the answer never explains ties.','Rubric example','correctness: 2 (clear)\ntie handling: 0 (absent)\nedge-case test: 1 (partial)\nexplanation: 1 (partial)', [['Dimension','Separates observable skills rather than collapsing everything into confidence.'],['0 / 1 / 2','A local rubric for absent, partial, and clear evidence.'],['Review evidence','Names what was actually missing: no tie rule or fixture.']], 'This toy round scores 4/8. That is practice feedback, not a prediction of a company’s hiring decision.'),
    e('Improve tie handling without memorizing the first answer.','Retry walkthrough','first prompt: latest order per customer\ndrill: two orders with the same timestamp\nnew prompt: top two products per region\nreview: deterministic row count versus keeping ties', [['Focused drill','Targets the weakest observed dimension.'],['New prompt','Tests whether the idea transfers rather than whether the exact answer was memorized.'],['Comparison','Uses the same rubric dimension to record concrete improvement.']], 'A good second answer explicitly chooses ROW_NUMBER versus a rank function and tests a tie fixture. The log preserves remaining weaknesses too.')
  ]
};
